export const providers = {
  // === Existing providers (keep exactly as-is) ===
  enbd: { nameEn: "Emirates NBD", logoUrl: "/logos/emirates-nbd.png", website: "https://www.emiratesnbd.com" },
  fab: { nameEn: "First Abu Dhabi Bank", logoUrl: "/logos/fab.png", website: "https://www.bankfab.com" },
  adcb: { nameEn: "ADCB", logoUrl: "/logos/adcb.png", website: "https://www.adcb.com" },
  mashreq: { nameEn: "Mashreq", logoUrl: "/logos/mashreq.png", website: "https://www.mashreqbank.com" },
  rakbank: { nameEn: "RAKBANK", logoUrl: "/logos/rakbank.png", website: "https://www.rakbank.ae" },
  cbd: { nameEn: "CBD", logoUrl: "/logos/cbd.png", website: "https://www.cbd.ae" },
  dib: { nameEn: "Dubai Islamic Bank", logoUrl: "/logos/dib.png", website: "https://www.dib.ae" },
  adib: { nameEn: "ADIB", logoUrl: "/logos/adib.png", website: "https://www.adib.ae" },
  ei: { nameEn: "Emirates Islamic", logoUrl: "/logos/emirates-islamic.png", website: "https://www.emiratesislamic.ae" },
  ajman: { nameEn: "Ajman Bank", logoUrl: "/logos/ajman-bank.png", website: "https://www.ajmanbank.ae" },
  sukoon: { nameEn: "Sukoon Insurance", logoUrl: "/logos/sukoon.png", website: "https://www.sukoon.com" },
  orient: { nameEn: "Orient Insurance", logoUrl: "/logos/orient.svg", website: "https://www.orientinsurance.ae" },
  axa: { nameEn: "AXA Insurance", logoUrl: "/logos/axa.svg", website: "https://www.axa-gulf.com" },
  adnic: { nameEn: "ADNIC", logoUrl: "/logos/adnic.svg", website: "https://www.adnic.ae" },
  daman: { nameEn: "Daman", logoUrl: "/logos/daman.svg", website: "https://www.damanhealth.ae" },
  du: { nameEn: "du", logoUrl: "/logos/du.png", website: "https://www.du.ae" },
  etisalat: { nameEn: "e& (Etisalat)", logoUrl: "/logos/etisalat.png", website: "https://www.etisalat.ae" },
  virgin: { nameEn: "Virgin Mobile UAE", logoUrl: "/logos/virgin-mobile.svg", website: "https://www.virginmobile.ae" },
  wio: { nameEn: "Wio Bank", logoUrl: "/logos/wio.svg", website: "https://www.wio.io" },
  liv: { nameEn: "Liv.", logoUrl: "/logos/liv.svg", website: "https://www.liv.me" },

  // === New providers ===
  tabby: { nameEn: "Tabby", logoUrl: "/logos/tabby.svg", website: "https://tabby.ai" },
  tamara: { nameEn: "Tamara", logoUrl: "/logos/tamara.svg", website: "https://tamara.co" },
  postpay: { nameEn: "Postpay", logoUrl: "/logos/postpay.svg", website: "https://postpay.io" },
  sarwa: { nameEn: "Sarwa", logoUrl: "/logos/sarwa.svg", website: "https://www.sarwa.co" },
  stashaway: { nameEn: "StashAway", logoUrl: "/logos/stashaway.svg", website: "https://www.stashaway.ae" },
  wealthface: { nameEn: "Wealthface", logoUrl: "/logos/wealthface.svg", website: "https://wealthface.com" },
  wahed: { nameEn: "Wahed Invest", logoUrl: "/logos/wahed.svg", website: "https://wahedinvest.com" },
  baraka: { nameEn: "Baraka", logoUrl: "/logos/baraka.svg", website: "https://www.getbaraka.com" },
  etoro: { nameEn: "eToro", logoUrl: "/logos/etoro.svg", website: "https://www.etoro.com" },
  saxo: { nameEn: "Saxo Bank", logoUrl: "/logos/saxo.svg", website: "https://www.home.saxo" },
  ibkr: { nameEn: "Interactive Brokers", logoUrl: "/logos/ibkr.svg", website: "https://www.interactivebrokers.com" },
  binance: { nameEn: "Binance", logoUrl: "/logos/binance.svg", website: "https://www.binance.com" },
  okx: { nameEn: "OKX", logoUrl: "/logos/okx.svg", website: "https://www.okx.com" },
  rain: { nameEn: "Rain", logoUrl: "/logos/rain.svg", website: "https://www.rain.com" },
  bitoasis: { nameEn: "BitOasis", logoUrl: "/logos/bitoasis.svg", website: "https://bitoasis.net" },
  wise: { nameEn: "Wise", logoUrl: "/logos/wise.svg", website: "https://wise.com" },
  revolut: { nameEn: "Revolut", logoUrl: "/logos/revolut.svg", website: "https://www.revolut.com" },
  alansari: { nameEn: "Al Ansari Exchange", logoUrl: "/logos/alansari.svg", website: "https://www.alansariexchange.com" },
  flexxpay: { nameEn: "FlexxPay", logoUrl: "/logos/flexxpay.svg", website: "https://flexxpay.com" },
  smartcrowd: { nameEn: "SmartCrowd", logoUrl: "/logos/smartcrowd.svg", website: "https://www.smartcrowd.ae" },
  stakeProp: { nameEn: "Stake", logoUrl: "/logos/stake.svg", website: "https://getstake.com" },
  pyypl: { nameEn: "Pyypl", logoUrl: "/logos/pyypl.svg", website: "https://www.pyypl.com" },
  yap: { nameEn: "YAP", logoUrl: "/logos/yap.svg", website: "https://www.yap.com" },
  telr: { nameEn: "Telr", logoUrl: "/logos/telr.svg", website: "https://telr.com" },
  paytabs: { nameEn: "PayTabs", logoUrl: "/logos/paytabs.svg", website: "https://site.paytabs.com" },
  stripe: { nameEn: "Stripe", logoUrl: "/logos/stripe.svg", website: "https://stripe.com" },
  tap: { nameEn: "Tap Payments", logoUrl: "/logos/tap.svg", website: "https://www.tap.company" },
  network: { nameEn: "Network International", logoUrl: "/logos/network.svg", website: "https://www.network.ae" },
  gig: { nameEn: "GIG Gulf", logoUrl: "/logos/gig.svg", website: "https://www.giggulf.ae" },
  hsbc: { nameEn: "HSBC", logoUrl: "/logos/hsbc.svg", website: "https://www.hsbc.ae" },
  zand: { nameEn: "Zand", logoUrl: "/logos/zand.svg", website: "https://www.zand.ae" },
  checkout: { nameEn: "Checkout.com", logoUrl: "/logos/checkout.svg", website: "https://www.checkout.com" },
  skywards: { nameEn: "Emirates Skywards", logoUrl: "/logos/skywards.svg", website: "https://www.emirates.com/skywards" },
  etihadguest: { nameEn: "Etihad Guest", logoUrl: "/logos/etihad-guest.svg", website: "https://www.etihadguest.com" },
  maf: { nameEn: "Majid Al Futtaim (Shukran)", logoUrl: "/logos/shukran.svg", website: "https://www.majidalfuttaim.com" },
  equiti: { nameEn: "Equiti", logoUrl: "/logos/equiti.svg", website: "https://www.equiti.com" },
  prypco: { nameEn: "PRYPCO", logoUrl: "/logos/prypco.svg", website: "https://prypco.com" },
  coinmena: { nameEn: "CoinMENA", logoUrl: "/logos/coinmena.svg", website: "https://www.coinmena.com" },
  emoney: { nameEn: "e& money", logoUrl: "/logos/e-money.svg", website: "https://www.eand.com" },
  payit: { nameEn: "payit", logoUrl: "/logos/payit.svg", website: "https://www.payit.ae" },
};
