import { sid } from "../_helpers";
import { providers } from "../_providers";

export const autoLoans: any[] = [
  {
    id: sid("al", 1),
    category: "auto_loan",
    nameEn: "Emirates NBD Auto Loan",
    nameAr: "قرض السيارات من بنك الإمارات دبي الوطني",
    descriptionEn: "Finance new and pre-owned vehicles with competitive rates and flexible repayment up to 60 months.",
    provider: providers.enbd,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "3.490",
    minAmount: "20000",
    maxAmount: "500000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Finance up to 80% of car value" },
      { en: "New and pre-owned vehicles" },
      { en: "Competitive reducing rate from 3.49%" },
      { en: "Quick approval process" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("al", 2),
    category: "auto_loan",
    nameEn: "FAB Auto Loan",
    nameAr: "قرض السيارات من بنك أبوظبي الأول",
    descriptionEn: "FAB auto loan with one of the lowest rates in the market and financing up to AED 500,000.",
    provider: providers.fab,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "2.990",
    minAmount: "20000",
    maxAmount: "500000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Lowest market rate from 2.99%" },
      { en: "Up to 80% finance for new cars" },
      { en: "Up to 60% for pre-owned cars" },
      { en: "Pre-approved offers for FAB customers" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("al", 3),
    category: "auto_loan",
    nameEn: "ADCB Auto Loan",
    nameAr: "قرض السيارات من بنك أبوظبي التجاري",
    descriptionEn: "ADCB auto finance with competitive rates, fast processing, and dealer partnerships across the UAE.",
    provider: providers.adcb,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "3.750",
    minAmount: "20000",
    maxAmount: "400000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Partnerships with major UAE dealers" },
      { en: "Free vehicle insurance for first year" },
      { en: "Quick disbursement" },
      { en: "Flexible tenure up to 60 months" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("al", 4),
    category: "auto_loan",
    nameEn: "Mashreq Auto Loan",
    nameAr: "قرض السيارات من بنك المشرق",
    descriptionEn: "Mashreq car loan with quick digital application and competitive rates for new vehicles.",
    provider: providers.mashreq,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "3.990",
    minAmount: "20000",
    maxAmount: "400000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.05",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.05, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Apply online or via Mashreq Neo app" },
      { en: "Finance up to 80% of vehicle value" },
      { en: "Approval within 30 minutes" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("al", 5),
    category: "auto_loan",
    nameEn: "DIB Auto Finance",
    nameAr: "تمويل السيارات من بنك دبي الإسلامي",
    descriptionEn: "Sharia-compliant vehicle finance from Dubai Islamic Bank with competitive profit rates.",
    provider: providers.dib,
    islamicCompliant: true,
    rateType: "reducing" as const,
    profitRate: "3.750",
    minAmount: "20000",
    maxAmount: "500000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "100% Sharia-compliant Murabaha" },
      { en: "Competitive profit rate" },
      { en: "New and pre-owned vehicles" },
      { en: "Free Takaful insurance" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("al", 6),
    category: "auto_loan",
    nameEn: "RAKBANK Auto Loan",
    nameAr: "قرض السيارات من راك بنك",
    descriptionEn: "RAKBANK auto finance with low minimum salary requirement and quick digital application.",
    provider: providers.rakbank,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "4.250",
    minAmount: "15000",
    maxAmount: "350000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "3000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Low minimum salary — AED 3,000" },
      { en: "Apply online via RAKmobile" },
      { en: "Up to 80% finance" },
      { en: "Free registration and insurance coordination" },
    ],
    eligibilityCriteria: {
      minSalary: 3000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
];
