import { sid } from "../_helpers";
import { providers } from "../_providers";

export const businessCreditCards: any[] = [
  {
    id: sid("bcc", 1),
    category: "business_credit_card",
    nameEn: "RAKBANK Titanium Business Card",
    nameAr: "بطاقة تيتانيوم للأعمال من راك بنك",
    descriptionEn: "RAKBANK Titanium Business Card designed for SME owners with cashback on business spends and simplified expense management.",
    provider: providers.rakbank,
    islamicCompliant: false,
    imageUrl: null,
    annualFee: "500",
    cashbackRate: "3",
    rewardType: "cashback",
    features: [
      { en: "Up to 3% cashback on office supplies and utilities" },
      { en: "Free supplementary cards for employees" },
      { en: "Detailed monthly expense statements by category" },
      { en: "Complimentary travel insurance up to AED 500,000" },
      { en: "Contactless and Apple Pay enabled" },
    ],
    fees: [
      { nameEn: "Annual Fee", amount: 500, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
      { nameEn: "Cash Advance Fee", amount: 3, type: "percentage" },
      { nameEn: "Foreign Currency Markup", amount: 2.5, type: "percentage" },
    ],
    eligibilityCriteria: {
      minAge: 21,
      employmentTypes: ["Business owner", "Self-employed"],
      minEmploymentMonths: 12,
      minAnnualRevenue: 500000,
    },
  },
  {
    id: sid("bcc", 2),
    category: "business_credit_card",
    nameEn: "ENBD Business Rewards Card",
    nameAr: "بطاقة مكافآت الأعمال من الإمارات دبي الوطني",
    descriptionEn: "Emirates NBD Business Rewards Card offering accelerated reward points on travel, dining, and corporate purchases.",
    provider: providers.enbd,
    islamicCompliant: false,
    imageUrl: null,
    annualFee: "750",
    cashbackRate: "0",
    rewardType: "points",
    features: [
      { en: "3x reward points on travel and airlines" },
      { en: "2x points on dining and entertainment" },
      { en: "Airport lounge access — 4 complimentary visits per year" },
      { en: "Expense management tools via ENBD Business Online" },
      { en: "Dedicated corporate helpline" },
    ],
    fees: [
      { nameEn: "Annual Fee", amount: 750, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 300, type: "fixed" },
      { nameEn: "Supplementary Card Fee", amount: 250, type: "fixed" },
      { nameEn: "Cash Advance Fee", amount: 3, type: "percentage" },
    ],
    eligibilityCriteria: {
      minAge: 21,
      employmentTypes: ["Business owner", "Self-employed"],
      minEmploymentMonths: 12,
      minAnnualRevenue: 750000,
    },
  },
  {
    id: sid("bcc", 3),
    category: "business_credit_card",
    nameEn: "Wio Business Card",
    nameAr: "بطاقة ويو للأعمال",
    descriptionEn: "Wio Bank's digital-first business card with real-time expense tracking, instant virtual cards, and cashback on all spends.",
    provider: providers.wio,
    islamicCompliant: false,
    imageUrl: null,
    annualFee: "0",
    cashbackRate: "1.5",
    rewardType: "cashback",
    features: [
      { en: "No annual fee — free for life" },
      { en: "1.5% cashback on all business purchases" },
      { en: "Instant virtual card issuance for employees" },
      { en: "Real-time expense tracking and categorization" },
      { en: "Set spending limits per card and employee" },
    ],
    fees: [
      { nameEn: "Annual Fee", amount: 0, type: "fixed" },
      { nameEn: "ATM Withdrawal (international)", amount: 10, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 1.5, type: "percentage" },
    ],
    eligibilityCriteria: {
      minAge: 21,
      employmentTypes: ["Business owner", "Freelancer"],
      minEmploymentMonths: 0,
    },
  },
  {
    id: sid("bcc", 4),
    category: "business_credit_card",
    nameEn: "FAB Business Card",
    nameAr: "بطاقة الأعمال من بنك أبوظبي الأول",
    descriptionEn: "First Abu Dhabi Bank Business Card with high credit limits, travel perks, and comprehensive business insurance coverage.",
    provider: providers.fab,
    islamicCompliant: false,
    imageUrl: null,
    annualFee: "1000",
    cashbackRate: "2",
    rewardType: "cashback",
    features: [
      { en: "Up to 2% cashback on all business spends" },
      { en: "High credit limits tailored for corporate needs" },
      { en: "Complimentary travel and purchase protection" },
      { en: "Priority airport lounge access — 6 visits per year" },
      { en: "Integration with FAB Business Online Banking" },
    ],
    fees: [
      { nameEn: "Annual Fee", amount: 1000, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 300, type: "fixed" },
      { nameEn: "Supplementary Card Fee", amount: 400, type: "fixed" },
      { nameEn: "Cash Advance Fee", amount: 3.5, type: "percentage" },
    ],
    eligibilityCriteria: {
      minAge: 21,
      employmentTypes: ["Business owner", "Self-employed"],
      minEmploymentMonths: 24,
      minAnnualRevenue: 1000000,
    },
  },
];
