import { sid } from "../_helpers";
import { providers } from "../_providers";

export const businessAccounts: any[] = [
  {
    id: sid("ba", 1),
    category: "business_account",
    nameEn: "Emirates NBD Business Account",
    nameAr: "حساب الأعمال من بنك الإمارات دبي الوطني",
    descriptionEn: "Full-service business current account from Emirates NBD with integrated digital banking and trade services.",
    provider: providers.enbd,
    islamicCompliant: false,
    imageUrl: null,
    monthlyFee: "50",
    minBalance: "25000",
    features: [
      { en: "Free online and mobile banking" },
      { en: "Integrated payroll services" },
      { en: "Multi-currency account options" },
      { en: "Dedicated business banking relationship manager" },
    ],
    fees: [
      { nameEn: "Monthly Maintenance Fee", amount: 50, type: "fixed" },
      { nameEn: "Below Minimum Balance Fee", amount: 100, type: "fixed" },
      { nameEn: "Cheque Book (25 leaves)", amount: 50, type: "fixed" },
    ],
  },
  {
    id: sid("ba", 2),
    category: "business_account",
    nameEn: "FAB Business One Account",
    nameAr: "حساب بزنس ون من بنك أبوظبي الأول",
    descriptionEn: "FAB's flagship business account with tiered pricing, global transaction capabilities and premium support.",
    provider: providers.fab,
    islamicCompliant: false,
    imageUrl: null,
    monthlyFee: "75",
    minBalance: "50000",
    features: [
      { en: "Waived fees with minimum balance of AED 50K" },
      { en: "Free unlimited domestic transfers" },
      { en: "Real-time cash management dashboard" },
      { en: "Access to trade finance and FX services" },
    ],
    fees: [
      { nameEn: "Monthly Maintenance Fee", amount: 75, type: "fixed" },
      { nameEn: "International Wire Transfer", amount: 50, type: "fixed" },
      { nameEn: "Cash Deposit Fee (over AED 100K)", amount: 0.1, type: "percentage" },
    ],
  },
  {
    id: sid("ba", 3),
    category: "business_account",
    nameEn: "Wio Business Account",
    nameAr: "حساب الأعمال من بنك ويو",
    descriptionEn: "Digital-first business account from Wio Bank with zero monthly fees and instant account opening.",
    provider: providers.wio,
    islamicCompliant: false,
    imageUrl: null,
    monthlyFee: "0",
    minBalance: "0",
    features: [
      { en: "Zero monthly fees" },
      { en: "Open an account in minutes via mobile app" },
      { en: "Free virtual and physical debit card" },
      { en: "Built-in invoicing and expense tracking" },
    ],
    fees: [
      { nameEn: "Monthly Maintenance Fee", amount: 0, type: "fixed" },
      { nameEn: "Domestic Transfer", amount: 0, type: "fixed" },
      { nameEn: "International Transfer", amount: 25, type: "fixed" },
    ],
  },
  {
    id: sid("ba", 4),
    category: "business_account",
    nameEn: "RAKBANK Business Account",
    nameAr: "حساب الأعمال من بنك رأس الخيمة",
    descriptionEn: "Straightforward business banking from RAKBANK with affordable pricing and easy onboarding for SMEs.",
    provider: providers.rakbank,
    islamicCompliant: false,
    imageUrl: null,
    monthlyFee: "25",
    minBalance: "10000",
    features: [
      { en: "Low monthly fee of AED 25" },
      { en: "Free zone and mainland company accounts" },
      { en: "Free first cheque book" },
      { en: "RAKvalue loyalty rewards on transactions" },
    ],
    fees: [
      { nameEn: "Monthly Maintenance Fee", amount: 25, type: "fixed" },
      { nameEn: "Below Minimum Balance Fee", amount: 75, type: "fixed" },
      { nameEn: "Statement Request Fee", amount: 25, type: "fixed" },
    ],
  },
];
