import { sid } from "../_helpers";
import { providers } from "../_providers";

export const businessLoans: any[] = [
  {
    id: sid("bl", 1),
    category: "business_loan",
    nameEn: "Emirates NBD Business Loan",
    nameAr: "قرض الأعمال من بنك الإمارات دبي الوطني",
    descriptionEn: "Working capital and expansion financing for SMEs with competitive rates and minimal documentation.",
    provider: providers.enbd,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "5.490",
    minAmount: "100000",
    maxAmount: "5000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.50",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.5, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Financing from AED 100K to AED 5M" },
      { en: "Minimal documentation required" },
      { en: "Flexible repayment terms" },
      { en: "Dedicated SME relationship manager" },
    ],
    eligibilityCriteria: {
      minAge: 21,
      employmentTypes: ["Business owner"],
      minEmploymentMonths: 24,
    },
  },
  {
    id: sid("bl", 2),
    category: "business_loan",
    nameEn: "FAB SME Business Finance",
    nameAr: "تمويل الأعمال الصغيرة من بنك أبوظبي الأول",
    descriptionEn: "FAB business loan for small and medium enterprises with quick processing and collateral-free options.",
    provider: providers.fab,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "4.990",
    minAmount: "100000",
    maxAmount: "10000000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.25",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.25, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Finance up to AED 10 million" },
      { en: "Collateral-free options for eligible SMEs" },
      { en: "Quick disbursement" },
      { en: "Trade finance and overdraft facilities" },
    ],
    eligibilityCriteria: {
      minAge: 21,
      employmentTypes: ["Business owner"],
      minEmploymentMonths: 12,
    },
  },
  {
    id: sid("bl", 3),
    category: "business_loan",
    nameEn: "Mashreq Business Banking Loan",
    nameAr: "قرض الأعمال المصرفية من المشرق",
    descriptionEn: "Mashreq business loan offering working capital and asset finance for growing businesses.",
    provider: providers.mashreq,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "5.250",
    minAmount: "50000",
    maxAmount: "3000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.50",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.5, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1.5, type: "percentage" },
    ],
    features: [
      { en: "Working capital and asset finance" },
      { en: "Digital application via Mashreq Business Banking" },
      { en: "Quick turnaround time" },
      { en: "Available to free zone companies" },
    ],
    eligibilityCriteria: {
      minAge: 21,
      employmentTypes: ["Business owner"],
      minEmploymentMonths: 12,
    },
  },
];
