import { sid } from "../_helpers";
import { providers } from "../_providers";

export const creditCards: any[] = [
  {
    id: sid("cc", 1),
    category: "credit_card",
    nameEn: "FAB Cashback Credit Card",
    nameAr: "بطاقة استرداد النقود من بنك أبوظبي الأول",
    descriptionEn: "Earn unlimited cashback on all your everyday spends with the FAB Cashback Credit Card.",
    provider: providers.fab,
    islamicCompliant: false,
    annualFee: "0",
    annualFeeWaiver: "Free for life",
    cashbackRate: "5",
    rewardType: "cashback",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "0",
    minSalary: "8000",
    imageUrl: "/products/fab-cashback.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 0, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
      { nameEn: "Cash Advance Fee", amount: 3, type: "percentage" },
    ],
    features: [
      { en: "Up to 5% cashback on groceries" },
      { en: "Up to 2% cashback on all other spends" },
      { en: "No annual fee — free for life" },
      { en: "Contactless payments enabled" },
      { en: "Free supplementary card" },
    ],
    eligibilityCriteria: {
      minSalary: 8000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 2),
    category: "credit_card",
    nameEn: "FAB World Elite Mastercard",
    nameAr: "بطاقة وورلد إيليت ماستركارد من بنك أبوظبي الأول",
    descriptionEn: "Premium World Elite Mastercard with airport lounge access, golf privileges, and luxury benefits.",
    provider: providers.fab,
    islamicCompliant: false,
    annualFee: "1575",
    annualFeeWaiver: "Spend AED 300,000/year",
    rewardType: "points",
    rewardRate: "3",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "525",
    minSalary: "50000",
    imageUrl: "/products/fab-world-elite.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 1575, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 300, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 2.75, type: "percentage" },
    ],
    features: [
      { en: "Unlimited airport lounge access worldwide" },
      { en: "Complimentary golf at premium courses" },
      { en: "3x reward points on international spends" },
      { en: "Travel insurance up to AED 3 million" },
      { en: "Concierge service 24/7" },
    ],
    eligibilityCriteria: {
      minSalary: 50000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 3),
    category: "credit_card",
    nameEn: "Emirates NBD Beyond Card",
    nameAr: "بطاقة بيوند من بنك الإمارات دبي الوطني",
    descriptionEn: "Premium metal credit card with up to 7 points per AED and access to exclusive lifestyle privileges.",
    provider: providers.enbd,
    islamicCompliant: false,
    annualFee: "1000",
    annualFeeWaiver: "Spend AED 200,000/year",
    rewardType: "points",
    rewardRate: "7",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "0",
    minSalary: "30000",
    imageUrl: "/products/enbd-cashback.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 1000, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 2.5, type: "percentage" },
    ],
    features: [
      { en: "Up to 7 Beyond points per AED on dining" },
      { en: "Free supplementary card" },
      { en: "Airport lounge access (6 visits/year)" },
      { en: "Premium metal card" },
      { en: "Valet parking at select locations" },
    ],
    eligibilityCriteria: {
      minSalary: 30000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 4),
    category: "credit_card",
    nameEn: "Emirates NBD GO Cashback Card",
    nameAr: "بطاقة جو كاش باك من بنك الإمارات دبي الوطني",
    descriptionEn: "No annual fee cashback credit card ideal for everyday spending and online shopping.",
    provider: providers.enbd,
    islamicCompliant: false,
    annualFee: "0",
    annualFeeWaiver: "Free for life",
    cashbackRate: "3",
    rewardType: "cashback",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "0",
    minSalary: "5000",
    imageUrl: "/products/enbd-dnata.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 0, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 200, type: "fixed" },
      { nameEn: "Cash Advance Fee", amount: 3, type: "percentage" },
    ],
    features: [
      { en: "Up to 3% cashback on online purchases" },
      { en: "1% cashback on all other spends" },
      { en: "No annual fee — free for life" },
      { en: "Instant card issuance via app" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 3,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 5),
    category: "credit_card",
    nameEn: "Mashreq Solitaire Visa Infinite",
    nameAr: "بطاقة سوليتير فيزا انفينيت من المشرق",
    descriptionEn: "Luxury credit card with Visa Infinite benefits, airport lounge access, and elite travel privileges.",
    provider: providers.mashreq,
    islamicCompliant: false,
    annualFee: "1050",
    annualFeeWaiver: "Spend AED 250,000/year",
    rewardType: "miles",
    rewardRate: "3",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "525",
    minSalary: "30000",
    imageUrl: "/products/mashreq-solitaire.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 1050, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 2.65, type: "percentage" },
    ],
    features: [
      { en: "3x Salaam Miles on travel & dining" },
      { en: "Unlimited airport lounge access" },
      { en: "Visa Infinite concierge" },
      { en: "Travel insurance up to AED 2 million" },
      { en: "Hotel & dining discounts worldwide" },
    ],
    eligibilityCriteria: {
      minSalary: 30000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 6),
    category: "credit_card",
    nameEn: "Mashreq Cashback Card",
    nameAr: "بطاقة كاش باك من المشرق",
    descriptionEn: "Flat-rate cashback credit card from Mashreq with no annual fee for the first year.",
    provider: providers.mashreq,
    islamicCompliant: false,
    annualFee: "315",
    annualFeeWaiver: "Free first year",
    cashbackRate: "3",
    rewardType: "cashback",
    interestFreeGraceDays: 52,
    supplementaryCardFee: "0",
    minSalary: "8000",
    imageUrl: "/products/mashreq-cashback.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 315, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 200, type: "fixed" },
      { nameEn: "Cash Advance Fee", amount: 3, type: "percentage" },
    ],
    features: [
      { en: "Up to 3% cashback on dining" },
      { en: "1% cashback on all spends" },
      { en: "Free first year annual fee" },
      { en: "Free supplementary card" },
    ],
    eligibilityCriteria: {
      minSalary: 8000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 7),
    category: "credit_card",
    nameEn: "ADCB TouchPoints Infinite Card",
    nameAr: "بطاقة تاتش بوينتس انفينيت من أبوظبي التجاري",
    descriptionEn: "Earn TouchPoints on every purchase and redeem for flights, hotel stays, or shopping vouchers.",
    provider: providers.adcb,
    islamicCompliant: false,
    annualFee: "525",
    annualFeeWaiver: "Spend AED 150,000/year",
    rewardType: "points",
    rewardRate: "5",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "0",
    minSalary: "15000",
    imageUrl: "/products/adcb-touchpoints.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 525, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 2.75, type: "percentage" },
    ],
    features: [
      { en: "5x TouchPoints on dining & grocery" },
      { en: "2x TouchPoints on all other spends" },
      { en: "Airport lounge access (4 visits/year)" },
      { en: "Free supplementary card" },
      { en: "Redeem points for flights, stays, vouchers" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 8),
    category: "credit_card",
    nameEn: "ADCB Traveller Card",
    nameAr: "بطاقة ترافيلر من أبوظبي التجاري",
    descriptionEn: "Travel-focused credit card with no foreign exchange markup and free lounge access.",
    provider: providers.adcb,
    islamicCompliant: false,
    annualFee: "750",
    annualFeeWaiver: "Spend AED 200,000/year",
    rewardType: "miles",
    rewardRate: "2",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "250",
    minSalary: "20000",
    imageUrl: "/products/adcb-traveller.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 750, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 0, type: "percentage" },
    ],
    features: [
      { en: "0% foreign currency markup" },
      { en: "2x miles on all international spends" },
      { en: "Complimentary airport lounge access" },
      { en: "Travel insurance coverage included" },
      { en: "Free airport transfers (2/year)" },
    ],
    eligibilityCriteria: {
      minSalary: 20000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 9),
    category: "credit_card",
    nameEn: "RAKBANK World Mastercard",
    nameAr: "بطاقة وورلد ماستركارد من راك بنك",
    descriptionEn: "All-round credit card with cashback, lounge access, and low income requirement.",
    provider: providers.rakbank,
    islamicCompliant: false,
    annualFee: "500",
    annualFeeWaiver: "Spend AED 100,000/year",
    cashbackRate: "4",
    rewardType: "cashback",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "0",
    minSalary: "10000",
    imageUrl: "/products/rakbank-world.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 500, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 200, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 2.75, type: "percentage" },
    ],
    features: [
      { en: "Up to 4% cashback on dining" },
      { en: "1% cashback on everything else" },
      { en: "2 free airport lounge visits/year" },
      { en: "Free supplementary card" },
      { en: "Exclusive Mastercard World offers" },
    ],
    eligibilityCriteria: {
      minSalary: 10000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 10),
    category: "credit_card",
    nameEn: "DIB Prime Visa Infinite Card",
    nameAr: "بطاقة برايم فيزا انفينيت من بنك دبي الإسلامي",
    descriptionEn: "Premium Sharia-compliant credit card from DIB with luxury travel benefits and Visa Infinite perks.",
    provider: providers.dib,
    islamicCompliant: true,
    annualFee: "945",
    annualFeeWaiver: "Spend AED 200,000/year",
    rewardType: "points",
    rewardRate: "4",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "0",
    minSalary: "25000",
    imageUrl: "/products/dib-prime.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 945, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
      { nameEn: "Cash Advance Fee", amount: 3, type: "percentage" },
    ],
    features: [
      { en: "Sharia-compliant — no interest charges" },
      { en: "4x reward points on travel & dining" },
      { en: "Unlimited airport lounge access" },
      { en: "Free supplementary card" },
      { en: "Visa Infinite luxury hotel collection" },
    ],
    eligibilityCriteria: {
      minSalary: 25000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 11),
    category: "credit_card",
    nameEn: "DIB Signature Card",
    nameAr: "بطاقة سيجنيتشر من بنك دبي الإسلامي",
    descriptionEn: "Sharia-compliant Visa Signature card with lifestyle benefits and competitive rewards.",
    provider: providers.dib,
    islamicCompliant: true,
    annualFee: "525",
    annualFeeWaiver: "Spend AED 120,000/year",
    rewardType: "points",
    rewardRate: "2",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "0",
    minSalary: "12000",
    imageUrl: "/products/dib-signature.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 525, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 200, type: "fixed" },
    ],
    features: [
      { en: "Sharia-compliant" },
      { en: "2x reward points on all purchases" },
      { en: "Airport lounge access (4 visits/year)" },
      { en: "Free supplementary card" },
      { en: "Dining and lifestyle discounts" },
    ],
    eligibilityCriteria: {
      minSalary: 12000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 12),
    category: "credit_card",
    nameEn: "CBD World Mastercard",
    nameAr: "بطاقة وورلد ماستركارد من بنك دبي التجاري",
    descriptionEn: "CBD World Mastercard with generous rewards and low annual fee. Great for everyday spending.",
    provider: providers.cbd,
    islamicCompliant: false,
    annualFee: "420",
    annualFeeWaiver: "Spend AED 100,000/year",
    cashbackRate: "3",
    rewardType: "cashback",
    interestFreeGraceDays: 52,
    supplementaryCardFee: "0",
    minSalary: "10000",
    imageUrl: "/products/cbd-world.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 420, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 225, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 2.75, type: "percentage" },
    ],
    features: [
      { en: "Up to 3% cashback on supermarkets & fuel" },
      { en: "1% cashback on all other spends" },
      { en: "Airport lounge access (2 visits/year)" },
      { en: "Free supplementary card" },
      { en: "Mastercard World privileges" },
    ],
    eligibilityCriteria: {
      minSalary: 10000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
];
