import { sid } from "../_helpers";
import { providers } from "../_providers";

export const debtManagement: any[] = [
  {
    id: sid("dm", 1),
    category: "debt_management",
    nameEn: "Emirates NBD Debt Consolidation Loan",
    nameAr: "قرض توحيد الديون من بنك الإمارات دبي الوطني",
    descriptionEn: "Consolidate multiple debts into a single loan with Emirates NBD — lower your monthly payments and simplify your finances.",
    provider: providers.enbd,
    islamicCompliant: false,
    imageUrl: null,
    rateType: "reducing",
    rateValue: "4.990",
    minAmount: "20000",
    maxAmount: "1500000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.05",
    minSalary: "5000",
    features: [
      { en: "Consolidate credit card and loan balances" },
      { en: "Single monthly repayment" },
      { en: "Reduced overall interest cost" },
      { en: "Flexible tenure up to 48 months" },
      { en: "Quick approval within 24 hours" },
    ],
    fees: [
      { nameEn: "Processing Fee", amount: 1.05, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
      { nameEn: "Insurance Fee", amount: 0.48, type: "percentage" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("dm", 2),
    category: "debt_management",
    nameEn: "Mashreq Debt Consolidation Plan",
    nameAr: "خطة توحيد الديون من مشرق",
    descriptionEn: "Combine your outstanding loans and credit card debts into one manageable plan with Mashreq at a competitive rate.",
    provider: providers.mashreq,
    islamicCompliant: false,
    imageUrl: null,
    rateType: "reducing",
    rateValue: "5.250",
    minAmount: "15000",
    maxAmount: "1000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.00",
    minSalary: "5000",
    features: [
      { en: "Merge up to 5 existing debts" },
      { en: "Potential savings on interest payments" },
      { en: "Fixed monthly installment" },
      { en: "Online application via Mashreq app" },
      { en: "Balance transfer from other banks" },
    ],
    fees: [
      { nameEn: "Processing Fee", amount: 1.0, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("dm", 3),
    category: "debt_management",
    nameEn: "ADCB Buyout & Consolidation Loan",
    nameAr: "قرض الشراء وتوحيد الديون من بنك أبوظبي التجاري",
    descriptionEn: "Transfer and consolidate your existing loans from other banks to ADCB with a lower rate and extended tenure.",
    provider: providers.adcb,
    islamicCompliant: false,
    imageUrl: null,
    rateType: "reducing",
    rateValue: "4.750",
    minAmount: "10000",
    maxAmount: "2000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.05",
    minSalary: "7000",
    features: [
      { en: "Buy out existing loans from other banks" },
      { en: "Consolidate all debts into one loan" },
      { en: "Lower interest rate than most credit cards" },
      { en: "Tenure up to 48 months" },
      { en: "Free life insurance coverage" },
    ],
    fees: [
      { nameEn: "Processing Fee", amount: 1.05, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
      { nameEn: "Insurance Fee", amount: 0.48, type: "percentage" },
    ],
    eligibilityCriteria: {
      minSalary: 7000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
];
