import { sid } from "../_helpers";
import { providers } from "../_providers";

export const digitalWallets: any[] = [
  {
    id: sid("dw", 1),
    category: "digital_wallet",
    nameEn: "payit by FAB",
    nameAr: "بي إت من بنك أبوظبي الأول",
    descriptionEn: "FAB's digital wallet payit for instant money transfers, bill payments, and contactless in-store payments across the UAE.",
    provider: providers.payit,
    islamicCompliant: false,
    imageUrl: null,
    features: [
      { en: "Instant peer-to-peer money transfers" },
      { en: "Pay bills for utilities, telecom, and government services" },
      { en: "Contactless payments via NFC" },
      { en: "Top up using any UAE debit or credit card" },
      { en: "Split bill feature for group expenses" },
    ],
    fees: [
      { nameEn: "Wallet-to-Wallet Transfer", amount: 0, type: "fixed" },
      { nameEn: "Bank Transfer Fee", amount: 2, type: "fixed" },
      { nameEn: "ATM Cash Withdrawal", amount: 5, type: "fixed" },
    ],
  },
  {
    id: sid("dw", 2),
    category: "digital_wallet",
    nameEn: "e& money",
    nameAr: "إي أند موني",
    descriptionEn: "e& money digital wallet for sending money locally and internationally, paying bills, and shopping online with your phone.",
    provider: providers.emoney,
    islamicCompliant: false,
    imageUrl: null,
    features: [
      { en: "International remittance to 200+ countries" },
      { en: "Bill payments for utilities and telecom" },
      { en: "Online and in-store payments via QR code" },
      { en: "Instant top-up from any bank card" },
      { en: "Loyalty rewards on transactions" },
    ],
    fees: [
      { nameEn: "Local Transfer Fee", amount: 0, type: "fixed" },
      { nameEn: "International Remittance Fee", amount: 10, type: "fixed" },
      { nameEn: "Cash Withdrawal Fee", amount: 3, type: "fixed" },
    ],
  },
  {
    id: sid("dw", 3),
    category: "digital_wallet",
    nameEn: "Mashreq NEO Wallet",
    nameAr: "محفظة ماشرق نيو",
    descriptionEn: "Mashreq NEO digital wallet offering instant account opening, a virtual debit card, and seamless mobile payments.",
    provider: providers.mashreq,
    islamicCompliant: false,
    imageUrl: null,
    features: [
      { en: "Open a wallet in minutes with Emirates ID" },
      { en: "Virtual and physical Visa debit card" },
      { en: "Free local money transfers to any UAE account" },
      { en: "Apple Pay and Samsung Pay compatible" },
      { en: "Budget tracking and spending insights" },
    ],
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
      { nameEn: "International Transfer Fee", amount: 15, type: "fixed" },
      { nameEn: "ATM Withdrawal (domestic)", amount: 2, type: "fixed" },
    ],
  },
  {
    id: sid("dw", 4),
    category: "digital_wallet",
    nameEn: "Pyypl Digital Wallet",
    nameAr: "محفظة بيبل الرقمية",
    descriptionEn: "Pyypl is a borderless digital wallet that lets you send money, shop online, and pay in-store — no bank account needed.",
    provider: providers.pyypl,
    islamicCompliant: false,
    imageUrl: null,
    features: [
      { en: "No bank account or credit check required" },
      { en: "Virtual Visa card for online shopping" },
      { en: "Send money to 50+ countries" },
      { en: "Top up via exchange houses or bank transfer" },
      { en: "Instant registration with passport or Emirates ID" },
    ],
    fees: [
      { nameEn: "Wallet-to-Wallet Transfer", amount: 0, type: "fixed" },
      { nameEn: "International Transfer Fee", amount: 8, type: "fixed" },
      { nameEn: "ATM Withdrawal Fee", amount: 5, type: "fixed" },
      { nameEn: "Card Top-up Fee", amount: 1.5, type: "percentage" },
    ],
  },
];
