import { sid } from "../_helpers";
import { providers } from "../_providers";

export const domesticHelperInsurance: any[] = [
  {
    id: sid("dhi", 1),
    category: "domestic_helper_insurance",
    nameEn: "Sukoon Domestic Worker Insurance",
    nameAr: "تأمين العمالة المنزلية من سكون",
    descriptionEn: "Comprehensive domestic worker insurance from Sukoon covering medical expenses, repatriation, and employer liability as required by UAE law.",
    provider: providers.sukoon,
    islamicCompliant: false,
    imageUrl: null,
    premiumMin: "600",
    premiumMax: "1200",
    coverageAmount: "250000",
    features: [
      { en: "Medical coverage up to AED 250,000" },
      { en: "Emergency and outpatient treatment included" },
      { en: "Repatriation of mortal remains coverage" },
      { en: "Employer liability protection" },
      { en: "Compliant with UAE visa requirements" },
    ],
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 25, type: "fixed" },
    ],
  },
  {
    id: sid("dhi", 2),
    category: "domestic_helper_insurance",
    nameEn: "GIG Gulf Helper Insurance",
    nameAr: "تأمين المساعد المنزلي من جي آي جي الخليج",
    descriptionEn: "GIG Gulf domestic helper insurance providing medical, accidental, and liability coverage for household employees in the UAE.",
    provider: providers.gig,
    islamicCompliant: false,
    imageUrl: null,
    premiumMin: "550",
    premiumMax: "1100",
    coverageAmount: "200000",
    features: [
      { en: "Inpatient and outpatient medical cover" },
      { en: "Personal accident coverage up to AED 50,000" },
      { en: "Dental and optical emergency treatment" },
      { en: "Maternity cover available as add-on" },
      { en: "Online policy purchase and renewal" },
    ],
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 20, type: "fixed" },
    ],
  },
  {
    id: sid("dhi", 3),
    category: "domestic_helper_insurance",
    nameEn: "ADNIC Domestic Helper Insurance",
    nameAr: "تأمين العمالة المنزلية من أدنيك",
    descriptionEn: "ADNIC domestic helper insurance offering affordable coverage for medical treatment, accidents, and legal liabilities for household staff.",
    provider: providers.adnic,
    islamicCompliant: false,
    imageUrl: null,
    premiumMin: "500",
    premiumMax: "950",
    coverageAmount: "150000",
    features: [
      { en: "Medical coverage up to AED 150,000" },
      { en: "Accidental death and disability benefit" },
      { en: "Emergency dental treatment cover" },
      { en: "24/7 helpline for medical emergencies" },
      { en: "Quick online claims processing" },
    ],
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 20, type: "fixed" },
    ],
  },
  {
    id: sid("dhi", 4),
    category: "domestic_helper_insurance",
    nameEn: "Daman Domestic Worker Insurance",
    nameAr: "تأمين العمالة المنزلية من ضمان",
    descriptionEn: "Daman domestic worker health insurance plan meeting Abu Dhabi and UAE federal requirements with comprehensive medical coverage.",
    provider: providers.daman,
    islamicCompliant: false,
    imageUrl: null,
    premiumMin: "650",
    premiumMax: "1400",
    coverageAmount: "300000",
    features: [
      { en: "Comprehensive inpatient and outpatient cover" },
      { en: "Abu Dhabi HAAD and DHA compliant plans" },
      { en: "Coverage up to AED 300,000" },
      { en: "Pharmacy and lab test coverage included" },
      { en: "Wide network of 2,000+ hospitals and clinics" },
    ],
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 30, type: "fixed" },
    ],
  },
];
