import { sid } from "../_helpers";
import { providers } from "../_providers";

export const educationLoans: any[] = [
  {
    id: sid("el", 1),
    category: "education_loan",
    nameEn: "ENBD Scholar Plus",
    nameAr: "سكولار بلس من الإمارات دبي الوطني",
    descriptionEn: "Emirates NBD Scholar Plus education loan covering tuition, accommodation, and living expenses for students in the UAE and abroad.",
    provider: providers.enbd,
    islamicCompliant: false,
    imageUrl: null,
    rateType: "reducing" as const,
    rateValue: "5.490",
    minAmount: "20000",
    maxAmount: "500000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.00",
    minSalary: "10000",
    features: [
      { en: "Covers tuition, books, and accommodation" },
      { en: "Flexible repayment up to 60 months" },
      { en: "Grace period during study term" },
      { en: "Available for UAE and international universities" },
      { en: "Quick online application and approval" },
    ],
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
    ],
    eligibilityCriteria: {
      minSalary: 10000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("el", 2),
    category: "education_loan",
    nameEn: "RAKBANK Education Loan",
    nameAr: "قرض التعليم من راك بنك",
    descriptionEn: "RAKBANK education loan for parents and students with competitive rates and simple documentation for local and overseas studies.",
    provider: providers.rakbank,
    islamicCompliant: false,
    imageUrl: null,
    rateType: "reducing" as const,
    rateValue: "5.990",
    minAmount: "10000",
    maxAmount: "300000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.25",
    minSalary: "7500",
    features: [
      { en: "Financing from AED 10K to AED 300K" },
      { en: "Repayment up to 48 months" },
      { en: "Minimal documentation required" },
      { en: "Covers schools, universities, and vocational training" },
    ],
    fees: [
      { nameEn: "Processing Fee", amount: 1.25, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
      { nameEn: "Late Payment Fee", amount: 200, type: "fixed" },
    ],
    eligibilityCriteria: {
      minSalary: 7500,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("el", 3),
    category: "education_loan",
    nameEn: "HSBC Student Loan",
    nameAr: "قرض الطالب من إتش إس بي سي",
    descriptionEn: "HSBC Student Loan designed for higher education with preferential rates for HSBC account holders and extended repayment periods.",
    provider: providers.hsbc,
    islamicCompliant: false,
    imageUrl: null,
    rateType: "reducing" as const,
    rateValue: "4.990",
    minAmount: "25000",
    maxAmount: "750000",
    minTenureMonths: 12,
    maxTenureMonths: 72,
    processingFeePercent: "0.75",
    minSalary: "15000",
    features: [
      { en: "Preferential rates for HSBC Premier customers" },
      { en: "Up to AED 750K for international universities" },
      { en: "Repayment up to 72 months" },
      { en: "Moratorium period up to 12 months" },
      { en: "Covers tuition and living expenses abroad" },
    ],
    fees: [
      { nameEn: "Processing Fee", amount: 0.75, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
      { nameEn: "Late Payment Fee", amount: 300, type: "fixed" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("el", 4),
    category: "education_loan",
    nameEn: "ADIB Education Finance",
    nameAr: "تمويل التعليم من مصرف أبوظبي الإسلامي",
    descriptionEn: "Sharia-compliant education financing from ADIB for local and international education with flexible Murabaha-based repayment.",
    provider: providers.adib,
    islamicCompliant: true,
    imageUrl: null,
    rateType: "reducing" as const,
    rateValue: "5.750",
    minAmount: "15000",
    maxAmount: "400000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.00",
    minSalary: "8000",
    features: [
      { en: "Sharia-compliant Murabaha structure" },
      { en: "Covers tuition, accommodation, and living costs" },
      { en: "Financing up to AED 400K" },
      { en: "No early settlement penalty for full payment" },
      { en: "Flexible repayment up to 60 months" },
    ],
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Late Payment Fee", amount: 200, type: "fixed" },
    ],
    eligibilityCriteria: {
      minSalary: 8000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
];
