import { sid } from "../_helpers";
import { providers } from "../_providers";

export const equipmentFinancing: any[] = [
  {
    id: sid("ef", 1),
    category: "equipment_financing",
    nameEn: "Emirates NBD Equipment Finance",
    nameAr: "تمويل المعدات من بنك الإمارات دبي الوطني",
    descriptionEn: "Finance machinery, vehicles and equipment for your business with Emirates NBD's flexible asset financing.",
    provider: providers.enbd,
    islamicCompliant: false,
    imageUrl: null,
    rateValue: "5.250",
    minAmount: "50000",
    maxAmount: "10000000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    features: [
      { en: "Finance up to 80% of equipment value" },
      { en: "New and pre-owned equipment eligible" },
      { en: "Fixed monthly installments" },
      { en: "Equipment serves as collateral" },
    ],
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Insurance Arrangement Fee", amount: 500, type: "fixed" },
    ],
  },
  {
    id: sid("ef", 2),
    category: "equipment_financing",
    nameEn: "ADCB Asset Finance",
    nameAr: "تمويل الأصول من بنك أبوظبي التجاري",
    descriptionEn: "ADCB asset finance solutions to acquire commercial vehicles, plant and industrial equipment.",
    provider: providers.adcb,
    islamicCompliant: false,
    imageUrl: null,
    rateValue: "5.490",
    minAmount: "100000",
    maxAmount: "15000000",
    minTenureMonths: 12,
    maxTenureMonths: 72,
    features: [
      { en: "Finance up to 85% of asset value" },
      { en: "Covers commercial vehicles, machinery and IT equipment" },
      { en: "Flexible repayment with seasonal structuring" },
      { en: "Fast-track approval for existing ADCB clients" },
    ],
    fees: [
      { nameEn: "Processing Fee", amount: 1.25, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
  },
  {
    id: sid("ef", 3),
    category: "equipment_financing",
    nameEn: "DIB Ijara Equipment Finance",
    nameAr: "تمويل المعدات بالإجارة من بنك دبي الإسلامي",
    descriptionEn: "Sharia-compliant Ijara-based equipment leasing from Dubai Islamic Bank for business assets.",
    provider: providers.dib,
    islamicCompliant: true,
    imageUrl: null,
    rateValue: "5.750",
    minAmount: "75000",
    maxAmount: "8000000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    features: [
      { en: "Fully Sharia-compliant Ijara structure" },
      { en: "Ownership transfers at end of lease term" },
      { en: "Covers industrial, medical and construction equipment" },
      { en: "Flexible down payment options from 10%" },
    ],
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Documentation Fee", amount: 1000, type: "fixed" },
    ],
  },
];
