import { sid } from "../_helpers";
import { providers } from "../_providers";

export const fixedDeposits: any[] = [
  {
    id: sid("fd", 1),
    category: "fixed_deposit",
    nameEn: "Emirates NBD Fixed Deposit",
    nameAr: "وديعة ثابتة من بنك الإمارات دبي الوطني",
    descriptionEn: "Secure your savings with Emirates NBD fixed deposit offering guaranteed returns and flexible tenures.",
    provider: providers.enbd,
    islamicCompliant: false,
    rateValue: "4.250",
    minAmount: "10000",
    minTenureMonths: 1,
    maxTenureMonths: 60,
    imageUrl: null,
    fees: [],
    features: [
      { en: "Guaranteed returns up to 4.25% p.a." },
      { en: "Tenures from 1 month to 5 years" },
      { en: "Auto-renewal option" },
      { en: "Capital protection — zero risk" },
    ],
    eligibilityCriteria: {
      minAge: 18,
      nationalities: ["All nationalities"],
    },
  },
  {
    id: sid("fd", 2),
    category: "fixed_deposit",
    nameEn: "FAB Term Deposit",
    nameAr: "وديعة لأجل من بنك أبوظبي الأول",
    descriptionEn: "FAB term deposit with attractive interest rates and the safety of the largest UAE bank.",
    provider: providers.fab,
    islamicCompliant: false,
    rateValue: "4.500",
    minAmount: "10000",
    minTenureMonths: 1,
    maxTenureMonths: 60,
    imageUrl: null,
    fees: [],
    features: [
      { en: "Up to 4.5% annual interest" },
      { en: "Backed by the UAE's largest bank" },
      { en: "Flexible tenure options" },
      { en: "Loan against deposit available" },
    ],
    eligibilityCriteria: {
      minAge: 18,
      nationalities: ["All nationalities"],
    },
  },
  {
    id: sid("fd", 3),
    category: "fixed_deposit",
    nameEn: "Mashreq Fixed Deposit",
    nameAr: "وديعة ثابتة من بنك المشرق",
    descriptionEn: "Mashreq bank fixed deposit with competitive rates and convenient online management.",
    provider: providers.mashreq,
    islamicCompliant: false,
    rateValue: "4.000",
    minAmount: "5000",
    minTenureMonths: 1,
    maxTenureMonths: 36,
    imageUrl: null,
    fees: [],
    features: [
      { en: "Up to 4% annual interest" },
      { en: "Lower minimum deposit at AED 5,000" },
      { en: "Manage via Mashreq Neo app" },
      { en: "Auto-renewal with updated rates" },
    ],
    eligibilityCriteria: {
      minAge: 18,
      nationalities: ["All nationalities"],
    },
  },
];
