import { sid } from "../_helpers";
import { providers } from "../_providers";

export const homeInternet: any[] = [
  {
    id: sid("hi", 1),
    category: "home_internet",
    nameEn: "du Home 500 Mbps",
    nameAr: "إنترنت منزلي 500 ميجابت من دو",
    descriptionEn: "High-speed home internet from du with 500 Mbps download speed, unlimited data, and free Wi-Fi router.",
    provider: providers.du,
    islamicCompliant: false,
    imageUrl: null,
    priceMonthly: "349",
    speed: "500 Mbps",
    contractMonths: 12,
    dataGb: "unlimited",
    features: [
      { en: "500 Mbps download speed" },
      { en: "Unlimited data usage" },
      { en: "Free Wi-Fi 6 router included" },
      { en: "Free installation" },
      { en: "24/7 technical support" },
    ],
    fees: [
      { nameEn: "Monthly Subscription", amount: 349, type: "fixed" },
      { nameEn: "Installation Fee", amount: 0, type: "fixed" },
    ],
  },
  {
    id: sid("hi", 2),
    category: "home_internet",
    nameEn: "du Home 1 Gbps",
    nameAr: "إنترنت منزلي 1 جيجابت من دو",
    descriptionEn: "Ultra-fast 1 Gbps home internet from du — ideal for streaming, gaming, and large households.",
    provider: providers.du,
    islamicCompliant: false,
    imageUrl: null,
    priceMonthly: "549",
    speed: "1 Gbps",
    contractMonths: 12,
    dataGb: "unlimited",
    features: [
      { en: "1 Gbps download speed" },
      { en: "Unlimited data usage" },
      { en: "Free Wi-Fi 6 mesh router system" },
      { en: "Free installation and setup" },
      { en: "Priority customer support" },
    ],
    fees: [
      { nameEn: "Monthly Subscription", amount: 549, type: "fixed" },
      { nameEn: "Installation Fee", amount: 0, type: "fixed" },
    ],
  },
  {
    id: sid("hi", 3),
    category: "home_internet",
    nameEn: "e& eLife Home 500 Mbps",
    nameAr: "إنترنت إي لايف 500 ميجابت من اتصالات",
    descriptionEn: "Reliable 500 Mbps home broadband from e& (Etisalat) with eLife TV bundle options and unlimited usage.",
    provider: providers.etisalat,
    islamicCompliant: false,
    imageUrl: null,
    priceMonthly: "389",
    speed: "500 Mbps",
    contractMonths: 12,
    dataGb: "unlimited",
    features: [
      { en: "500 Mbps download speed" },
      { en: "Unlimited data usage" },
      { en: "Optional eLife TV bundle" },
      { en: "Free router and installation" },
      { en: "Parental controls included" },
    ],
    fees: [
      { nameEn: "Monthly Subscription", amount: 389, type: "fixed" },
      { nameEn: "Installation Fee", amount: 0, type: "fixed" },
    ],
  },
  {
    id: sid("hi", 4),
    category: "home_internet",
    nameEn: "e& eLife Home 1 Gbps",
    nameAr: "إنترنت إي لايف 1 جيجابت من اتصالات",
    descriptionEn: "Blazing fast 1 Gbps fibre broadband from e& (Etisalat) with premium eLife entertainment and smart home features.",
    provider: providers.etisalat,
    islamicCompliant: false,
    imageUrl: null,
    priceMonthly: "589",
    speed: "1 Gbps",
    contractMonths: 12,
    dataGb: "unlimited",
    features: [
      { en: "1 Gbps symmetrical fibre speed" },
      { en: "Unlimited data usage" },
      { en: "Premium eLife TV channels included" },
      { en: "Free mesh Wi-Fi system" },
      { en: "Smart home integration support" },
    ],
    fees: [
      { nameEn: "Monthly Subscription", amount: 589, type: "fixed" },
      { nameEn: "Installation Fee", amount: 0, type: "fixed" },
    ],
  },
];
