import { sid } from "../_helpers";
import { providers } from "../_providers";

export const kidsAccounts: any[] = [
  {
    id: sid("ka", 1),
    category: "kids_account",
    nameEn: "ADIB Amwali Junior Account",
    nameAr: "حساب أموالي جونيور من مصرف أبوظبي الإسلامي",
    descriptionEn: "Sharia-compliant savings account for children from ADIB, teaching financial literacy while building savings with competitive profit rates.",
    provider: providers.adib,
    islamicCompliant: true,
    imageUrl: null,
    minBalance: "0",
    rateValue: "2.000",
    features: [
      { en: "Sharia-compliant savings account for ages 0-17" },
      { en: "No minimum balance requirement" },
      { en: "Up to 2% annual profit rate" },
      { en: "Prepaid card for children aged 10+" },
      { en: "Parental controls and spending alerts" },
      { en: "Financial literacy tools and games" },
    ],
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
    ],
  },
  {
    id: sid("ka", 2),
    category: "kids_account",
    nameEn: "Mashreq NEO NXT Account",
    nameAr: "حساب ماشرق نيو نكست",
    descriptionEn: "Mashreq NEO NXT digital account for teenagers with a prepaid Visa card, budgeting tools, and parental oversight.",
    provider: providers.mashreq,
    islamicCompliant: false,
    imageUrl: null,
    minBalance: "0",
    rateValue: "1.500",
    features: [
      { en: "Digital account for ages 12-17" },
      { en: "Prepaid Visa card with custom designs" },
      { en: "Real-time spending notifications for parents" },
      { en: "Savings goals and pocket money features" },
      { en: "Fully managed via Mashreq NEO app" },
    ],
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
      { nameEn: "Card Replacement Fee", amount: 25, type: "fixed" },
    ],
  },
  {
    id: sid("ka", 3),
    category: "kids_account",
    nameEn: "DIB Shaatir Savings Account",
    nameAr: "حساب شاطر للتوفير من بنك دبي الإسلامي",
    descriptionEn: "Dubai Islamic Bank Shaatir savings account for children with Sharia-compliant profit sharing and educational savings plans.",
    provider: providers.dib,
    islamicCompliant: true,
    imageUrl: null,
    minBalance: "500",
    rateValue: "2.250",
    features: [
      { en: "Sharia-compliant savings for ages 0-17" },
      { en: "Up to 2.25% annual expected profit rate" },
      { en: "Minimum opening balance AED 500" },
      { en: "Free Shaatir prepaid card for ages 10+" },
      { en: "Rewards for regular savings deposits" },
    ],
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
    ],
  },
  {
    id: sid("ka", 4),
    category: "kids_account",
    nameEn: "ENBD EarlySaver Account",
    nameAr: "حساب التوفير المبكر من الإمارات دبي الوطني",
    descriptionEn: "Emirates NBD EarlySaver account helping parents save for their children's future with competitive interest and flexible deposits.",
    provider: providers.enbd,
    islamicCompliant: false,
    imageUrl: null,
    minBalance: "1000",
    rateValue: "2.750",
    features: [
      { en: "Competitive interest rate up to 2.75%" },
      { en: "Open for children aged 0-17" },
      { en: "Standing instruction for automatic monthly deposits" },
      { en: "Linked to parent's ENBD account for easy transfers" },
      { en: "Bonus interest for no withdrawals in a year" },
    ],
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
      { nameEn: "Early Withdrawal Penalty", amount: 50, type: "fixed" },
    ],
  },
];
