import { sid } from "../_helpers";
import { providers } from "../_providers";

export const loyaltyPrograms: any[] = [
  {
    id: sid("lp", 1),
    category: "loyalty_program",
    nameEn: "Emirates Skywards",
    nameAr: "سكاي واردز الإمارات",
    descriptionEn: "Earn and redeem Skywards Miles on flights, hotels, shopping and everyday spending with Emirates airline's loyalty program.",
    provider: providers.skywards,
    islamicCompliant: false,
    imageUrl: null,
    features: [
      { en: "Earn miles on Emirates & flydubai flights" },
      { en: "400+ retail & dining partners" },
      { en: "4 tier levels: Blue, Silver, Gold, Platinum" },
      { en: "Miles never expire for active members" },
      { en: "Redeem for flight upgrades, hotels, and experiences" },
    ],
    fees: [],
  },
  {
    id: sid("lp", 2),
    category: "loyalty_program",
    nameEn: "Etihad Guest",
    nameAr: "ضيف الاتحاد",
    descriptionEn: "Etihad Guest rewards frequent flyers with miles on Etihad Airways and partners, redeemable for flights, upgrades, and lifestyle rewards.",
    provider: providers.etihadguest,
    islamicCompliant: false,
    imageUrl: null,
    features: [
      { en: "Earn miles on Etihad and partner airline flights" },
      { en: "3 tier levels: Guest, Silver, Gold" },
      { en: "Redeem miles for flights, upgrades, and duty-free" },
      { en: "200+ retail and dining earn partners in the UAE" },
      { en: "Family pooling — share miles with up to 9 members" },
    ],
    fees: [],
  },
  {
    id: sid("lp", 3),
    category: "loyalty_program",
    nameEn: "FAB Rewards",
    nameAr: "مكافآت بنك أبوظبي الأول",
    descriptionEn: "FAB Rewards lets you earn points on every credit card and debit card transaction, redeemable for cashback, travel, and shopping.",
    provider: providers.fab,
    islamicCompliant: false,
    imageUrl: null,
    features: [
      { en: "Earn 1-3 points per AED spent on FAB cards" },
      { en: "Redeem for cashback, air miles, or gift vouchers" },
      { en: "Points never expire while card is active" },
      { en: "Bonus points on select merchant categories" },
      { en: "Convert to Emirates Skywards or Etihad Guest miles" },
    ],
    fees: [],
  },
  {
    id: sid("lp", 4),
    category: "loyalty_program",
    nameEn: "ADCB Touchpoints",
    nameAr: "تاتش بوينتس من بنك أبوظبي التجاري",
    descriptionEn: "ADCB Touchpoints is one of the UAE's largest bank loyalty programs, earning you points on banking, shopping, and dining.",
    provider: providers.adcb,
    islamicCompliant: false,
    imageUrl: null,
    features: [
      { en: "Earn points on credit card and debit card spends" },
      { en: "Redeem at 1,200+ retail and dining partners" },
      { en: "Instant redemption at POS — no vouchers needed" },
      { en: "Earn points on loan and mortgage payments too" },
      { en: "Points valid for 3 years from date of earn" },
    ],
    fees: [],
  },
  {
    id: sid("lp", 5),
    category: "loyalty_program",
    nameEn: "Shukran by Majid Al Futtaim",
    nameAr: "شكراً من مجموعة ماجد الفطيم",
    descriptionEn: "Shukran is Majid Al Futtaim's loyalty program earning points across Carrefour, Mall of the Emirates, VOX Cinemas, and 1,000+ brands.",
    provider: providers.maf,
    islamicCompliant: false,
    imageUrl: null,
    features: [
      { en: "Earn points at Carrefour, VOX, Ski Dubai, and more" },
      { en: "1,000+ participating brands across MAF properties" },
      { en: "Instant redemption at checkout — 1 point = AED 0.0025" },
      { en: "Exclusive member-only discounts and early access" },
      { en: "Free to join — no annual fee or membership charges" },
    ],
    fees: [],
  },
];
