import { sid } from "../_helpers";
import { providers } from "../_providers";

export const merchantAccounts: any[] = [
  {
    id: sid("ma", 1),
    category: "merchant_account",
    nameEn: "Telr Merchant Account",
    nameAr: "حساب التاجر من تلر",
    descriptionEn: "Telr payment gateway for UAE businesses supporting online payments, invoicing, and social commerce with multi-currency acceptance.",
    provider: providers.telr,
    islamicCompliant: false,
    imageUrl: null,
    features: [
      { en: "Accept Visa, Mastercard, AMEX, and Apple Pay" },
      { en: "Multi-currency support — 120+ currencies" },
      { en: "Social commerce tools for Instagram and WhatsApp" },
      { en: "Hosted and integrated checkout options" },
      { en: "Real-time analytics and transaction reporting" },
    ],
    fees: [
      { nameEn: "Transaction Fee (local cards)", amount: 2.49, type: "percentage" },
      { nameEn: "Transaction Fee (international cards)", amount: 2.99, type: "percentage" },
      { nameEn: "Fixed Fee per Transaction", amount: 1, type: "fixed" },
      { nameEn: "Monthly Subscription", amount: 349, type: "fixed" },
    ],
  },
  {
    id: sid("ma", 2),
    category: "merchant_account",
    nameEn: "PayTabs Business Account",
    nameAr: "حساب التاجر من بيتابس",
    descriptionEn: "PayTabs merchant solution for MENA businesses with plug-and-play payment pages, recurring billing, and developer-friendly APIs.",
    provider: providers.paytabs,
    islamicCompliant: false,
    imageUrl: null,
    features: [
      { en: "Ready-made payment pages — no coding required" },
      { en: "Recurring billing and subscription management" },
      { en: "Developer APIs and SDKs for custom integration" },
      { en: "Fraud prevention and 3D Secure authentication" },
      { en: "Multi-currency and multi-language support" },
    ],
    fees: [
      { nameEn: "Transaction Fee (local cards)", amount: 2.65, type: "percentage" },
      { nameEn: "Transaction Fee (international cards)", amount: 3.2, type: "percentage" },
      { nameEn: "Fixed Fee per Transaction", amount: 1, type: "fixed" },
      { nameEn: "Setup Fee", amount: 0, type: "fixed" },
    ],
  },
  {
    id: sid("ma", 3),
    category: "merchant_account",
    nameEn: "Stripe UAE",
    nameAr: "سترايب الإمارات",
    descriptionEn: "Stripe's full-stack payment platform for UAE businesses offering seamless online checkout, subscriptions, and global payment acceptance.",
    provider: providers.stripe,
    islamicCompliant: false,
    imageUrl: null,
    features: [
      { en: "Accept payments from 195+ countries" },
      { en: "Pre-built UI components and hosted checkout" },
      { en: "Subscription billing and invoicing" },
      { en: "Advanced fraud detection with Stripe Radar" },
      { en: "Comprehensive developer APIs and documentation" },
    ],
    fees: [
      { nameEn: "Transaction Fee (local cards)", amount: 2.5, type: "percentage" },
      { nameEn: "Transaction Fee (international cards)", amount: 3.5, type: "percentage" },
      { nameEn: "Fixed Fee per Transaction", amount: 1, type: "fixed" },
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
    ],
  },
  {
    id: sid("ma", 4),
    category: "merchant_account",
    nameEn: "Tap Payments Merchant Account",
    nameAr: "حساب التاجر من تاب بيمنتس",
    descriptionEn: "Tap Payments provides UAE merchants with a unified payment gateway supporting cards, Apple Pay, KNET, and regional payment methods.",
    provider: providers.tap,
    islamicCompliant: false,
    imageUrl: null,
    features: [
      { en: "Unified gateway for cards, wallets, and BNPL" },
      { en: "Apple Pay and Google Pay support" },
      { en: "goCollect — payment links via SMS and WhatsApp" },
      { en: "Dashboard with real-time settlement tracking" },
      { en: "Plugins for Shopify, WooCommerce, and Magento" },
    ],
    fees: [
      { nameEn: "Transaction Fee (local cards)", amount: 2.0, type: "percentage" },
      { nameEn: "Transaction Fee (international cards)", amount: 2.75, type: "percentage" },
      { nameEn: "Fixed Fee per Transaction", amount: 0.5, type: "fixed" },
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
    ],
  },
];
