import { sid } from "../_helpers";
import { providers } from "../_providers";

export const mobilePlans: any[] = [
  {
    id: sid("mp", 1),
    category: "mobile_plan",
    nameEn: "du Power Plan 200",
    nameAr: "خطة باور 200 من دو",
    descriptionEn: "du postpaid plan with generous data allowance, unlimited local calls, and entertainment perks.",
    provider: providers.du,
    islamicCompliant: false,
    priceMonthly: "200",
    dataGb: "40",
    minutes: "unlimited",
    contractMonths: 12,
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Subscription", amount: 200, type: "fixed" },
      { nameEn: "SIM Card Fee", amount: 55, type: "fixed" },
    ],
    features: [
      { en: "40 GB monthly data" },
      { en: "Unlimited local calls" },
      { en: "Free OSN streaming" },
      { en: "Data rollover to next month" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("mp", 2),
    category: "mobile_plan",
    nameEn: "du Flex Plan 100",
    nameAr: "خطة فلكس 100 من دو",
    descriptionEn: "Budget-friendly du postpaid plan with 10 GB data and flexible national minutes.",
    provider: providers.du,
    islamicCompliant: false,
    priceMonthly: "100",
    dataGb: "10",
    minutes: "250",
    contractMonths: 12,
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Subscription", amount: 100, type: "fixed" },
      { nameEn: "SIM Card Fee", amount: 55, type: "fixed" },
    ],
    features: [
      { en: "10 GB monthly data" },
      { en: "250 national minutes" },
      { en: "Unlimited du-to-du calls" },
      { en: "No commitment plans available" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("mp", 3),
    category: "mobile_plan",
    nameEn: "e& Unlimited Plan 300",
    nameAr: "خطة أنليمتد 300 من اتصالات",
    descriptionEn: "Premium e& (Etisalat) postpaid plan with unlimited data, calls, and exclusive perks.",
    provider: providers.etisalat,
    islamicCompliant: false,
    priceMonthly: "300",
    dataGb: "unlimited",
    minutes: "unlimited",
    contractMonths: 12,
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Subscription", amount: 300, type: "fixed" },
      { nameEn: "SIM Card Fee", amount: 55, type: "fixed" },
    ],
    features: [
      { en: "Unlimited data" },
      { en: "Unlimited local and national calls" },
      { en: "Free roaming in select countries" },
      { en: "Starzplay and other OTT subscriptions included" },
      { en: "Premium customer service" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("mp", 4),
    category: "mobile_plan",
    nameEn: "e& Go Plan 150",
    nameAr: "خطة جو 150 من اتصالات",
    descriptionEn: "Mid-tier e& (Etisalat) postpaid plan with balanced data, calls, and entertainment bundles.",
    provider: providers.etisalat,
    islamicCompliant: false,
    priceMonthly: "150",
    dataGb: "20",
    minutes: "unlimited",
    contractMonths: 12,
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Subscription", amount: 150, type: "fixed" },
      { nameEn: "SIM Card Fee", amount: 55, type: "fixed" },
    ],
    features: [
      { en: "20 GB monthly data" },
      { en: "Unlimited local calls" },
      { en: "Free Anghami Plus subscription" },
      { en: "Data rollover available" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("mp", 5),
    category: "mobile_plan",
    nameEn: "Virgin Mobile Go Big 199",
    nameAr: "خطة جو بيج 199 من فيرجن موبايل",
    descriptionEn: "Flexible SIM-only plan from Virgin Mobile UAE with generous data and zero commitment.",
    provider: providers.virgin,
    islamicCompliant: false,
    priceMonthly: "199",
    dataGb: "50",
    minutes: "unlimited",
    contractMonths: 0,
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Subscription", amount: 199, type: "fixed" },
    ],
    features: [
      { en: "50 GB monthly data" },
      { en: "Unlimited local calls & SMS" },
      { en: "No contract — cancel anytime" },
      { en: "Manage everything via app" },
      { en: "Free eSIM activation" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("mp", 6),
    category: "mobile_plan",
    nameEn: "Virgin Mobile Start 59",
    nameAr: "خطة ستارت 59 من فيرجن موبايل",
    descriptionEn: "Affordable SIM-only plan from Virgin Mobile for light users. No contract needed.",
    provider: providers.virgin,
    islamicCompliant: false,
    priceMonthly: "59",
    dataGb: "3",
    minutes: "60",
    contractMonths: 0,
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Subscription", amount: 59, type: "fixed" },
    ],
    features: [
      { en: "3 GB monthly data" },
      { en: "60 national minutes" },
      { en: "No contract — cancel anytime" },
      { en: "Manage everything via app" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
];
