import { sid } from "../_helpers";
import { providers } from "../_providers";

export const mortgages: any[] = [
  {
    id: sid("mg", 1),
    category: "mortgage",
    nameEn: "Emirates NBD Home Loan",
    nameAr: "قرض السكن من بنك الإمارات دبي الوطني",
    descriptionEn: "Fixed-rate mortgage with low rates and flexible tenures up to 25 years for UAE residents and nationals.",
    provider: providers.enbd,
    islamicCompliant: false,
    rateType: "fixed" as const,
    rateValue: "3.990",
    minAmount: "200000",
    maxAmount: "15000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "15000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Property Valuation Fee", amount: 3000, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Fixed rate for up to 5 years" },
      { en: "Up to 80% LTV for UAE nationals" },
      { en: "Up to 75% LTV for expats" },
      { en: "Free property valuation" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("mg", 2),
    category: "mortgage",
    nameEn: "FAB Home Loan",
    nameAr: "قرض السكن من بنك أبوظبي الأول",
    descriptionEn: "First Abu Dhabi Bank mortgage with competitive rates starting from 3.49% and high loan amounts.",
    provider: providers.fab,
    islamicCompliant: false,
    rateType: "variable" as const,
    rateValue: "3.490",
    minAmount: "250000",
    maxAmount: "20000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "15000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Valuation Fee", amount: 2625, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Competitive variable rate from 3.49%" },
      { en: "Finance up to AED 20 million" },
      { en: "Up to 80% LTV for nationals" },
      { en: "Mortgage life insurance included" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("mg", 3),
    category: "mortgage",
    nameEn: "ADCB Home Loan",
    nameAr: "قرض السكن من بنك أبوظبي التجاري",
    descriptionEn: "ADCB mortgage with fixed-rate options, fast approval, and dedicated relationship managers.",
    provider: providers.adcb,
    islamicCompliant: false,
    rateType: "fixed" as const,
    rateValue: "3.990",
    minAmount: "200000",
    maxAmount: "15000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.05",
    earlySettlementFeePercent: "1.00",
    minSalary: "15000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.05, type: "percentage" },
      { nameEn: "Valuation Fee", amount: 3150, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Fixed rate for 1, 3, or 5 years" },
      { en: "Dedicated relationship manager" },
      { en: "Online mortgage calculator" },
      { en: "Pre-approval in 48 hours" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("mg", 4),
    category: "mortgage",
    nameEn: "Mashreq Home Loan",
    nameAr: "قرض السكن من بنك المشرق",
    descriptionEn: "Mashreq mortgage with flexible rate options and a streamlined digital application process.",
    provider: providers.mashreq,
    islamicCompliant: false,
    rateType: "variable" as const,
    rateValue: "4.250",
    minAmount: "200000",
    maxAmount: "10000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "15000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Valuation Fee", amount: 2625, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Digital mortgage application" },
      { en: "Flexible rate options" },
      { en: "Buyout existing mortgage at better rates" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("mg", 5),
    category: "mortgage",
    nameEn: "DIB Home Finance",
    nameAr: "تمويل السكن من بنك دبي الإسلامي",
    descriptionEn: "Sharia-compliant home finance from Dubai Islamic Bank based on Diminishing Musharaka structure.",
    provider: providers.dib,
    islamicCompliant: true,
    rateType: "reducing" as const,
    profitRate: "3.990",
    minAmount: "200000",
    maxAmount: "15000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "15000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Valuation Fee", amount: 2625, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Sharia-compliant Diminishing Musharaka" },
      { en: "Competitive profit rates" },
      { en: "Up to 80% finance for UAE nationals" },
      { en: "Free Takaful coverage" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("mg", 6),
    category: "mortgage",
    nameEn: "ADIB Home Finance",
    nameAr: "تمويل السكن من مصرف أبوظبي الإسلامي",
    descriptionEn: "ADIB Sharia-compliant home finance with fixed profit rates and tenure up to 25 years.",
    provider: providers.adib,
    islamicCompliant: true,
    rateType: "fixed" as const,
    profitRate: "4.250",
    minAmount: "200000",
    maxAmount: "10000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.05",
    earlySettlementFeePercent: "1.00",
    minSalary: "15000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.05, type: "percentage" },
      { nameEn: "Valuation Fee", amount: 3000, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Fixed profit rate for initial period" },
      { en: "Sharia-compliant Ijarah Muntahia Bittamleek" },
      { en: "Up to AED 10 million finance" },
      { en: "Free Takaful insurance" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("mg", 7),
    category: "mortgage",
    nameEn: "Emirates Islamic Home Finance",
    nameAr: "تمويل السكن من الإمارات الإسلامي",
    descriptionEn: "Emirates Islamic Sharia-compliant home finance with competitive profit rates and fast processing.",
    provider: providers.ei,
    islamicCompliant: true,
    rateType: "reducing" as const,
    profitRate: "3.750",
    minAmount: "200000",
    maxAmount: "12000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "15000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Valuation Fee", amount: 2625, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Competitive Islamic profit rates" },
      { en: "Part of Emirates NBD Group" },
      { en: "Quick pre-approval" },
      { en: "Suitable for ready and off-plan properties" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("mg", 8),
    category: "mortgage",
    nameEn: "RAKBANK Home Loan",
    nameAr: "قرض السكن من راك بنك",
    descriptionEn: "RAKBANK mortgage with competitive rates and fast approvals for both UAE nationals and residents.",
    provider: providers.rakbank,
    islamicCompliant: false,
    rateType: "fixed" as const,
    rateValue: "4.490",
    minAmount: "150000",
    maxAmount: "10000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "12000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Valuation Fee", amount: 2500, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Fixed rate for initial period" },
      { en: "Lower minimum salary requirement" },
      { en: "Fast approval process" },
      { en: "Mortgage buyout option" },
    ],
    eligibilityCriteria: {
      minSalary: 12000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
];
