import { sid } from "../_helpers";
import { providers } from "../_providers";

export const personalLoans: any[] = [
  {
    id: sid("pl", 1),
    category: "personal_loan",
    nameEn: "Emirates NBD Personal Loan",
    nameAr: "قرض شخصي من بنك الإمارات دبي الوطني",
    descriptionEn: "Competitive personal loan from Emirates NBD with flexible repayment terms up to 48 months and quick approval.",
    provider: providers.enbd,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "4.990",
    minAmount: "10000",
    maxAmount: "1000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.05",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.05, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
      { nameEn: "Insurance Fee", amount: 0.48, type: "percentage" },
    ],
    features: [
      { en: "Salary transfer not required for select employers" },
      { en: "Loan disbursement within 30 minutes" },
      { en: "Balance transfer option available" },
      { en: "Free life insurance coverage" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 2),
    category: "personal_loan",
    nameEn: "FAB Personal Loan",
    nameAr: "قرض شخصي من بنك أبوظبي الأول",
    descriptionEn: "First Abu Dhabi Bank personal loan offering one of the lowest rates in the market with salary transfer.",
    provider: providers.fab,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "3.990",
    minAmount: "10000",
    maxAmount: "2000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Lowest interest rate with salary transfer" },
      { en: "Up to AED 2 million financing" },
      { en: "Quick online application" },
      { en: "Pre-approved offers for FAB customers" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 3,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 3),
    category: "personal_loan",
    nameEn: "ADCB Personal Loan",
    nameAr: "قرض شخصي من بنك أبوظبي التجاري",
    descriptionEn: "ADCB personal loan with instant approval and competitive rates for salaried professionals.",
    provider: providers.adcb,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "4.490",
    minAmount: "10000",
    maxAmount: "1500000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Instant approval for pre-qualified customers" },
      { en: "Free credit life insurance" },
      { en: "Flexible repayment tenure" },
      { en: "Top-up facility available" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 4),
    category: "personal_loan",
    nameEn: "Mashreq Personal Loan",
    nameAr: "قرض شخصي من بنك المشرق",
    descriptionEn: "Mashreq personal loan with fast processing and attractive rates for new and existing customers.",
    provider: providers.mashreq,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "4.750",
    minAmount: "10000",
    maxAmount: "1000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.25",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.25, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Up to 48 months repayment period" },
      { en: "Cash in account within 24 hours" },
      { en: "No guarantor required" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 5),
    category: "personal_loan",
    nameEn: "RAKBANK Personal Loan",
    nameAr: "قرض شخصي من راك بنك",
    descriptionEn: "RAKBANK personal loan with low rates and fast approval. Salary transfer option gives the best rates.",
    provider: providers.rakbank,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "4.250",
    minAmount: "5000",
    maxAmount: "750000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "3000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Lowest minimum salary requirement at AED 3,000" },
      { en: "Quick approval within minutes" },
      { en: "Free credit life insurance" },
      { en: "Apply online or via app" },
    ],
    eligibilityCriteria: {
      minSalary: 3000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 6),
    category: "personal_loan",
    nameEn: "CBD Personal Loan",
    nameAr: "قرض شخصي من بنك دبي التجاري",
    descriptionEn: "Commercial Bank of Dubai personal loan with straightforward terms and no hidden charges.",
    provider: providers.cbd,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "4.990",
    minAmount: "10000",
    maxAmount: "500000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Transparent pricing with no hidden fees" },
      { en: "Fixed monthly installments" },
      { en: "Salary transfer benefits" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 7),
    category: "personal_loan",
    nameEn: "DIB Personal Finance – Al Islami",
    nameAr: "التمويل الشخصي الإسلامي من بنك دبي الإسلامي",
    descriptionEn: "Sharia-compliant personal finance from Dubai Islamic Bank based on Murabaha structure.",
    provider: providers.dib,
    islamicCompliant: true,
    rateType: "reducing" as const,
    profitRate: "4.490",
    minAmount: "10000",
    maxAmount: "1500000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "100% Sharia-compliant Murabaha structure" },
      { en: "No interest — profit rate only" },
      { en: "Salary transfer and non-salary transfer options" },
      { en: "Free Takaful coverage" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 8),
    category: "personal_loan",
    nameEn: "ADIB Personal Finance",
    nameAr: "التمويل الشخصي من مصرف أبوظبي الإسلامي",
    descriptionEn: "Abu Dhabi Islamic Bank personal finance with Sharia-compliant Murabaha structure and competitive profit rates.",
    provider: providers.adib,
    islamicCompliant: true,
    rateType: "reducing" as const,
    profitRate: "4.750",
    minAmount: "10000",
    maxAmount: "1000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.05",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.05, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Sharia-compliant Murabaha personal finance" },
      { en: "Competitive profit rate" },
      { en: "Quick disbursement" },
      { en: "Free Takaful insurance" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 9),
    category: "personal_loan",
    nameEn: "Emirates Islamic Personal Finance",
    nameAr: "التمويل الشخصي من الإمارات الإسلامي",
    descriptionEn: "Emirates Islamic personal finance based on commodity Murabaha. Competitive rates for salary transfer customers.",
    provider: providers.ei,
    islamicCompliant: true,
    rateType: "reducing" as const,
    profitRate: "4.250",
    minAmount: "10000",
    maxAmount: "1000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Sharia-compliant commodity Murabaha" },
      { en: "Part of Emirates NBD Group" },
      { en: "Attractive rates for salary transfer" },
      { en: "Instant disbursement for existing customers" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 3,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 10),
    category: "personal_loan",
    nameEn: "Ajman Bank Personal Finance",
    nameAr: "التمويل الشخصي من مصرف عجمان",
    descriptionEn: "Ajman Bank Islamic personal finance with simple documentation and Sharia-compliant structure.",
    provider: providers.ajman,
    islamicCompliant: true,
    rateType: "reducing" as const,
    profitRate: "5.490",
    minAmount: "10000",
    maxAmount: "500000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.25",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.25, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Fully Sharia-compliant" },
      { en: "Simple documentation" },
      { en: "Flexible tenure up to 48 months" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
];
