import { sid } from "../_helpers";
import { providers } from "../_providers";

export const savingsAccounts: any[] = [
  {
    id: sid("sa", 1),
    category: "savings_account",
    nameEn: "Emirates NBD Savings Account",
    nameAr: "حساب التوفير من بنك الإمارات دبي الوطني",
    descriptionEn: "Earn competitive interest on your savings with zero minimum balance and easy access to funds.",
    provider: providers.enbd,
    islamicCompliant: false,
    rateValue: "2.500",
    minAmount: "0",
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Up to 2.5% annual interest" },
      { en: "No minimum balance required" },
      { en: "Free online banking and mobile app" },
      { en: "Link to ENBD current account" },
    ],
    eligibilityCriteria: {
      minSalary: 0,
      nationalities: ["All nationalities"],
      minAge: 18,
    },
  },
  {
    id: sid("sa", 2),
    category: "savings_account",
    nameEn: "FAB Savings Account",
    nameAr: "حساب التوفير من بنك أبوظبي الأول",
    descriptionEn: "FAB savings account with tiered interest rates — earn more as your balance grows.",
    provider: providers.fab,
    islamicCompliant: false,
    rateValue: "3.000",
    minAmount: "3000",
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
      { nameEn: "Below Min Balance Fee", amount: 25, type: "fixed" },
    ],
    features: [
      { en: "Up to 3% annual interest on high balances" },
      { en: "Tiered interest structure" },
      { en: "Free debit card" },
      { en: "Manage via FAB Mobile" },
    ],
    eligibilityCriteria: {
      minSalary: 0,
      nationalities: ["All nationalities"],
      minAge: 18,
    },
  },
  {
    id: sid("sa", 3),
    category: "savings_account",
    nameEn: "ADCB Savings Account",
    nameAr: "حساب التوفير من بنك أبوظبي التجاري",
    descriptionEn: "ADCB savings account with competitive rates and integrated TouchPoints rewards.",
    provider: providers.adcb,
    islamicCompliant: false,
    rateValue: "2.000",
    minAmount: "3000",
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Up to 2% annual interest" },
      { en: "Earn ADCB TouchPoints" },
      { en: "Free transfers between ADCB accounts" },
      { en: "Online goal-based savings" },
    ],
    eligibilityCriteria: {
      minSalary: 0,
      nationalities: ["All nationalities"],
      minAge: 18,
    },
  },
  {
    id: sid("sa", 4),
    category: "savings_account",
    nameEn: "Mashreq Neo Savings",
    nameAr: "حساب توفير مشرق نيو",
    descriptionEn: "Digital-first savings account from Mashreq with attractive rates and zero paperwork.",
    provider: providers.mashreq,
    islamicCompliant: false,
    rateValue: "3.500",
    minAmount: "0",
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Up to 3.5% annual interest" },
      { en: "Open account in minutes via app" },
      { en: "Zero minimum balance" },
      { en: "Instant fund transfers" },
    ],
    eligibilityCriteria: {
      minSalary: 0,
      nationalities: ["All nationalities"],
      minAge: 18,
    },
  },
  {
    id: sid("sa", 5),
    category: "savings_account",
    nameEn: "Wio Save",
    nameAr: "حساب التوفير من ويو",
    descriptionEn: "Digital bank savings account from Wio with one of the highest interest rates in the UAE.",
    provider: providers.wio,
    islamicCompliant: false,
    rateValue: "4.500",
    minAmount: "0",
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "4.5% annual interest — highest in UAE" },
      { en: "No minimum balance" },
      { en: "100% digital — open in 5 minutes" },
      { en: "CBUAE regulated" },
      { en: "Instant withdrawals to Wio current account" },
    ],
    eligibilityCriteria: {
      minSalary: 0,
      nationalities: ["UAE nationals", "UAE residents"],
      minAge: 18,
    },
  },
  {
    id: sid("sa", 6),
    category: "savings_account",
    nameEn: "Liv. Savings Account",
    nameAr: "حساب التوفير من ليف",
    descriptionEn: "Liv. digital savings account by Emirates NBD with competitive rates and a fully digital experience.",
    provider: providers.liv,
    islamicCompliant: false,
    rateValue: "3.000",
    minAmount: "0",
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Up to 3% annual interest" },
      { en: "Goal-based savings pots" },
      { en: "Zero fees on everything" },
      { en: "Social banking features" },
    ],
    eligibilityCriteria: {
      minSalary: 0,
      nationalities: ["All nationalities"],
      minAge: 18,
    },
  },
];
