import { sid } from "../_helpers";
import { providers } from "../_providers";

export const smeLoans: any[] = [
  {
    id: sid("sme", 1),
    category: "sme_loan",
    nameEn: "Emirates NBD Business Loan",
    nameAr: "قرض الأعمال من بنك الإمارات دبي الوطني",
    descriptionEn: "Flexible business financing for UAE SMEs with competitive rates and quick approval.",
    provider: providers.enbd,
    islamicCompliant: false,
    imageUrl: null,
    rateType: "reducing" as const,
    rateValue: "5.490",
    minAmount: "50000",
    maxAmount: "5000000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.00",
    minSalary: 50000,
    features: [
      { en: "Quick approval within 48 hours" },
      { en: "No collateral for loans up to AED 500K" },
      { en: "Dedicated relationship manager" },
      { en: "Flexible repayment schedules" },
    ],
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    eligibilityCriteria: {
      minSalary: 50000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Business Owner"],
    },
  },
  {
    id: sid("sme", 2),
    category: "sme_loan",
    nameEn: "FAB SME Finance",
    nameAr: "تمويل المشاريع الصغيرة من بنك أبوظبي الأول",
    descriptionEn: "Comprehensive SME financing solutions from FAB with flexible tenures and competitive pricing.",
    provider: providers.fab,
    islamicCompliant: false,
    imageUrl: null,
    rateType: "reducing" as const,
    rateValue: "4.990",
    minAmount: "100000",
    maxAmount: "10000000",
    minTenureMonths: 12,
    maxTenureMonths: 72,
    processingFeePercent: "1.25",
    minSalary: 100000,
    features: [
      { en: "Finance up to AED 10 million" },
      { en: "Collateral-free options for eligible businesses" },
      { en: "Quick disbursement within 3 business days" },
      { en: "Dedicated SME banking team" },
    ],
    fees: [
      { nameEn: "Processing Fee", amount: 1.25, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
      { nameEn: "Late Payment Fee", amount: 200, type: "fixed" },
    ],
    eligibilityCriteria: {
      minSalary: 100000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Business Owner"],
    },
  },
  {
    id: sid("sme", 3),
    category: "sme_loan",
    nameEn: "RAKBANK Business Loan",
    nameAr: "قرض الأعمال من بنك رأس الخيمة",
    descriptionEn: "RAKBANK SME financing designed for small businesses with simplified documentation and fast processing.",
    provider: providers.rakbank,
    islamicCompliant: false,
    imageUrl: null,
    rateType: "reducing" as const,
    rateValue: "5.750",
    minAmount: "50000",
    maxAmount: "3000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.50",
    minSalary: 30000,
    features: [
      { en: "Simplified documentation for existing RAKBANK clients" },
      { en: "Financing for startups with 1 year of operations" },
      { en: "Online application and tracking" },
      { en: "Free zone and mainland companies eligible" },
    ],
    fees: [
      { nameEn: "Processing Fee", amount: 1.5, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1.5, type: "percentage" },
    ],
    eligibilityCriteria: {
      minSalary: 30000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Business Owner"],
    },
  },
  {
    id: sid("sme", 4),
    category: "sme_loan",
    nameEn: "DIB Business Finance",
    nameAr: "تمويل الأعمال من بنك دبي الإسلامي",
    descriptionEn: "Sharia-compliant business financing from Dubai Islamic Bank with Murabaha and Ijara structures.",
    provider: providers.dib,
    islamicCompliant: true,
    imageUrl: null,
    rateType: "reducing" as const,
    rateValue: "5.990",
    minAmount: "100000",
    maxAmount: "7000000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.25",
    minSalary: 75000,
    features: [
      { en: "Fully Sharia-compliant Murabaha structure" },
      { en: "Available for trading, manufacturing and services" },
      { en: "No early settlement penalty for full settlement" },
      { en: "Dedicated Islamic business banking advisor" },
    ],
    fees: [
      { nameEn: "Processing Fee", amount: 1.25, type: "percentage" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
    ],
    eligibilityCriteria: {
      minSalary: 75000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Business Owner"],
    },
  },
];
