// ---------------------------------------------------------------------------
// Static product data for all major UAE financial/telecom categories.
// Used as a fallback when the API server is not running so compare pages
// render real-looking content out of the box.
// ---------------------------------------------------------------------------

/* ------------------------------------------------------------------ helpers */

/** Deterministic pseudo-UUID so IDs are stable across renders. */
function sid(prefix: string, n: number): string {
  const hex = (s: string) =>
    Array.from(s)
      .map((c) => c.charCodeAt(0).toString(16).padStart(2, "0"))
      .join("");
  const base = hex(`${prefix}-${n}`).padEnd(32, "0").slice(0, 32);
  return [base.slice(0, 8), base.slice(8, 12), base.slice(12, 16), base.slice(16, 20), base.slice(20, 32)].join("-");
}

/* ---------------------------------------------------------------- providers */

const providers = {
  enbd: { nameEn: "Emirates NBD", logoUrl: "/logos/emirates-nbd.png", website: "https://www.emiratesnbd.com" },
  fab: { nameEn: "First Abu Dhabi Bank", logoUrl: "/logos/fab.png", website: "https://www.bankfab.com" },
  adcb: { nameEn: "ADCB", logoUrl: "/logos/adcb.png", website: "https://www.adcb.com" },
  mashreq: { nameEn: "Mashreq", logoUrl: "/logos/mashreq.png", website: "https://www.mashreqbank.com" },
  rakbank: { nameEn: "RAKBANK", logoUrl: "/logos/rakbank.png", website: "https://www.rakbank.ae" },
  cbd: { nameEn: "CBD", logoUrl: "/logos/cbd.png", website: "https://www.cbd.ae" },
  dib: { nameEn: "Dubai Islamic Bank", logoUrl: "/logos/dib.png", website: "https://www.dib.ae" },
  adib: { nameEn: "ADIB", logoUrl: "/logos/adib.png", website: "https://www.adib.ae" },
  ei: { nameEn: "Emirates Islamic", logoUrl: "/logos/emirates-islamic.png", website: "https://www.emiratesislamic.ae" },
  ajman: { nameEn: "Ajman Bank", logoUrl: "/logos/ajman-bank.png", website: "https://www.ajmanbank.ae" },
  sukoon: { nameEn: "Sukoon Insurance", logoUrl: "/logos/sukoon.png", website: "https://www.sukoon.com" },
  orient: { nameEn: "Orient Insurance", logoUrl: "/logos/orient.svg", website: "https://www.orientinsurance.ae" },
  axa: { nameEn: "AXA Insurance", logoUrl: "/logos/axa.svg", website: "https://www.axa-gulf.com" },
  adnic: { nameEn: "ADNIC", logoUrl: "/logos/adnic.svg", website: "https://www.adnic.ae" },
  daman: { nameEn: "Daman", logoUrl: "/logos/daman.svg", website: "https://www.damanhealth.ae" },
  du: { nameEn: "du", logoUrl: "/logos/du.png", website: "https://www.du.ae" },
  etisalat: { nameEn: "e& (Etisalat)", logoUrl: "/logos/etisalat.png", website: "https://www.etisalat.ae" },
  virgin: { nameEn: "Virgin Mobile UAE", logoUrl: "/logos/virgin-mobile.svg", website: "https://www.virginmobile.ae" },
  wio: { nameEn: "Wio Bank", logoUrl: "/logos/wio.svg", website: "https://www.wio.io" },
  liv: { nameEn: "Liv.", logoUrl: "/logos/liv.svg", website: "https://www.liv.me" },
};

/* ========================================================================== */
/*  PERSONAL LOANS (10)                                                       */
/* ========================================================================== */

const personalLoans: any[] = [
  {
    id: sid("pl", 1),
    category: "personal_loan",
    nameEn: "Emirates NBD Personal Loan",
    nameAr: "قرض شخصي من بنك الإمارات دبي الوطني",
    descriptionEn: "Competitive personal loan from Emirates NBD with flexible repayment terms up to 48 months and quick approval.",
    provider: providers.enbd,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "4.990",
    minAmount: "10000",
    maxAmount: "1000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.05",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.05, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
      { nameEn: "Insurance Fee", amount: 0.48, type: "percentage" },
    ],
    features: [
      { en: "Salary transfer not required for select employers" },
      { en: "Loan disbursement within 30 minutes" },
      { en: "Balance transfer option available" },
      { en: "Free life insurance coverage" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 2),
    category: "personal_loan",
    nameEn: "FAB Personal Loan",
    nameAr: "قرض شخصي من بنك أبوظبي الأول",
    descriptionEn: "First Abu Dhabi Bank personal loan offering one of the lowest rates in the market with salary transfer.",
    provider: providers.fab,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "3.990",
    minAmount: "10000",
    maxAmount: "2000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Lowest interest rate with salary transfer" },
      { en: "Up to AED 2 million financing" },
      { en: "Quick online application" },
      { en: "Pre-approved offers for FAB customers" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 3,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 3),
    category: "personal_loan",
    nameEn: "ADCB Personal Loan",
    nameAr: "قرض شخصي من بنك أبوظبي التجاري",
    descriptionEn: "ADCB personal loan with instant approval and competitive rates for salaried professionals.",
    provider: providers.adcb,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "4.490",
    minAmount: "10000",
    maxAmount: "1500000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Instant approval for pre-qualified customers" },
      { en: "Free credit life insurance" },
      { en: "Flexible repayment tenure" },
      { en: "Top-up facility available" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 4),
    category: "personal_loan",
    nameEn: "Mashreq Personal Loan",
    nameAr: "قرض شخصي من بنك المشرق",
    descriptionEn: "Mashreq personal loan with fast processing and attractive rates for new and existing customers.",
    provider: providers.mashreq,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "4.750",
    minAmount: "10000",
    maxAmount: "1000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.25",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.25, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Up to 48 months repayment period" },
      { en: "Cash in account within 24 hours" },
      { en: "No guarantor required" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 5),
    category: "personal_loan",
    nameEn: "RAKBANK Personal Loan",
    nameAr: "قرض شخصي من راك بنك",
    descriptionEn: "RAKBANK personal loan with low rates and fast approval. Salary transfer option gives the best rates.",
    provider: providers.rakbank,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "4.250",
    minAmount: "5000",
    maxAmount: "750000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "3000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Lowest minimum salary requirement at AED 3,000" },
      { en: "Quick approval within minutes" },
      { en: "Free credit life insurance" },
      { en: "Apply online or via app" },
    ],
    eligibilityCriteria: {
      minSalary: 3000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 6),
    category: "personal_loan",
    nameEn: "CBD Personal Loan",
    nameAr: "قرض شخصي من بنك دبي التجاري",
    descriptionEn: "Commercial Bank of Dubai personal loan with straightforward terms and no hidden charges.",
    provider: providers.cbd,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "4.990",
    minAmount: "10000",
    maxAmount: "500000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Transparent pricing with no hidden fees" },
      { en: "Fixed monthly installments" },
      { en: "Salary transfer benefits" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 7),
    category: "personal_loan",
    nameEn: "DIB Personal Finance – Al Islami",
    nameAr: "التمويل الشخصي الإسلامي من بنك دبي الإسلامي",
    descriptionEn: "Sharia-compliant personal finance from Dubai Islamic Bank based on Murabaha structure.",
    provider: providers.dib,
    islamicCompliant: true,
    rateType: "reducing" as const,
    profitRate: "4.490",
    minAmount: "10000",
    maxAmount: "1500000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "100% Sharia-compliant Murabaha structure" },
      { en: "No interest — profit rate only" },
      { en: "Salary transfer and non-salary transfer options" },
      { en: "Free Takaful coverage" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 8),
    category: "personal_loan",
    nameEn: "ADIB Personal Finance",
    nameAr: "التمويل الشخصي من مصرف أبوظبي الإسلامي",
    descriptionEn: "Abu Dhabi Islamic Bank personal finance with Sharia-compliant Murabaha structure and competitive profit rates.",
    provider: providers.adib,
    islamicCompliant: true,
    rateType: "reducing" as const,
    profitRate: "4.750",
    minAmount: "10000",
    maxAmount: "1000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.05",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.05, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Sharia-compliant Murabaha personal finance" },
      { en: "Competitive profit rate" },
      { en: "Quick disbursement" },
      { en: "Free Takaful insurance" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 9),
    category: "personal_loan",
    nameEn: "Emirates Islamic Personal Finance",
    nameAr: "التمويل الشخصي من الإمارات الإسلامي",
    descriptionEn: "Emirates Islamic personal finance based on commodity Murabaha. Competitive rates for salary transfer customers.",
    provider: providers.ei,
    islamicCompliant: true,
    rateType: "reducing" as const,
    profitRate: "4.250",
    minAmount: "10000",
    maxAmount: "1000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Sharia-compliant commodity Murabaha" },
      { en: "Part of Emirates NBD Group" },
      { en: "Attractive rates for salary transfer" },
      { en: "Instant disbursement for existing customers" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 3,
      minAge: 21,
    },
  },
  {
    id: sid("pl", 10),
    category: "personal_loan",
    nameEn: "Ajman Bank Personal Finance",
    nameAr: "التمويل الشخصي من مصرف عجمان",
    descriptionEn: "Ajman Bank Islamic personal finance with simple documentation and Sharia-compliant structure.",
    provider: providers.ajman,
    islamicCompliant: true,
    rateType: "reducing" as const,
    profitRate: "5.490",
    minAmount: "10000",
    maxAmount: "500000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.25",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.25, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Fully Sharia-compliant" },
      { en: "Simple documentation" },
      { en: "Flexible tenure up to 48 months" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
];

/* ========================================================================== */
/*  CREDIT CARDS (12)                                                         */
/* ========================================================================== */

const creditCards: any[] = [
  {
    id: sid("cc", 1),
    category: "credit_card",
    nameEn: "FAB Cashback Credit Card",
    nameAr: "بطاقة استرداد النقود من بنك أبوظبي الأول",
    descriptionEn: "Earn unlimited cashback on all your everyday spends with the FAB Cashback Credit Card.",
    provider: providers.fab,
    islamicCompliant: false,
    annualFee: "0",
    annualFeeWaiver: "Free for life",
    cashbackRate: "5",
    rewardType: "cashback",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "0",
    minSalary: "8000",
    imageUrl: "/products/fab-cashback.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 0, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
      { nameEn: "Cash Advance Fee", amount: 3, type: "percentage" },
    ],
    features: [
      { en: "Up to 5% cashback on groceries" },
      { en: "Up to 2% cashback on all other spends" },
      { en: "No annual fee — free for life" },
      { en: "Contactless payments enabled" },
      { en: "Free supplementary card" },
    ],
    eligibilityCriteria: {
      minSalary: 8000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 2),
    category: "credit_card",
    nameEn: "FAB World Elite Mastercard",
    nameAr: "بطاقة وورلد إيليت ماستركارد من بنك أبوظبي الأول",
    descriptionEn: "Premium World Elite Mastercard with airport lounge access, golf privileges, and luxury benefits.",
    provider: providers.fab,
    islamicCompliant: false,
    annualFee: "1575",
    annualFeeWaiver: "Spend AED 300,000/year",
    rewardType: "points",
    rewardRate: "3",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "525",
    minSalary: "50000",
    imageUrl: "/products/fab-world-elite.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 1575, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 300, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 2.75, type: "percentage" },
    ],
    features: [
      { en: "Unlimited airport lounge access worldwide" },
      { en: "Complimentary golf at premium courses" },
      { en: "3x reward points on international spends" },
      { en: "Travel insurance up to AED 3 million" },
      { en: "Concierge service 24/7" },
    ],
    eligibilityCriteria: {
      minSalary: 50000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 3),
    category: "credit_card",
    nameEn: "Emirates NBD Beyond Card",
    nameAr: "بطاقة بيوند من بنك الإمارات دبي الوطني",
    descriptionEn: "Premium metal credit card with up to 7 points per AED and access to exclusive lifestyle privileges.",
    provider: providers.enbd,
    islamicCompliant: false,
    annualFee: "1000",
    annualFeeWaiver: "Spend AED 200,000/year",
    rewardType: "points",
    rewardRate: "7",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "0",
    minSalary: "30000",
    imageUrl: "/products/enbd-cashback.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 1000, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 2.5, type: "percentage" },
    ],
    features: [
      { en: "Up to 7 Beyond points per AED on dining" },
      { en: "Free supplementary card" },
      { en: "Airport lounge access (6 visits/year)" },
      { en: "Premium metal card" },
      { en: "Valet parking at select locations" },
    ],
    eligibilityCriteria: {
      minSalary: 30000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 4),
    category: "credit_card",
    nameEn: "Emirates NBD GO Cashback Card",
    nameAr: "بطاقة جو كاش باك من بنك الإمارات دبي الوطني",
    descriptionEn: "No annual fee cashback credit card ideal for everyday spending and online shopping.",
    provider: providers.enbd,
    islamicCompliant: false,
    annualFee: "0",
    annualFeeWaiver: "Free for life",
    cashbackRate: "3",
    rewardType: "cashback",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "0",
    minSalary: "5000",
    imageUrl: "/products/enbd-dnata.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 0, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 200, type: "fixed" },
      { nameEn: "Cash Advance Fee", amount: 3, type: "percentage" },
    ],
    features: [
      { en: "Up to 3% cashback on online purchases" },
      { en: "1% cashback on all other spends" },
      { en: "No annual fee — free for life" },
      { en: "Instant card issuance via app" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 3,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 5),
    category: "credit_card",
    nameEn: "Mashreq Solitaire Visa Infinite",
    nameAr: "بطاقة سوليتير فيزا انفينيت من المشرق",
    descriptionEn: "Luxury credit card with Visa Infinite benefits, airport lounge access, and elite travel privileges.",
    provider: providers.mashreq,
    islamicCompliant: false,
    annualFee: "1050",
    annualFeeWaiver: "Spend AED 250,000/year",
    rewardType: "miles",
    rewardRate: "3",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "525",
    minSalary: "30000",
    imageUrl: "/products/mashreq-solitaire.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 1050, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 2.65, type: "percentage" },
    ],
    features: [
      { en: "3x Salaam Miles on travel & dining" },
      { en: "Unlimited airport lounge access" },
      { en: "Visa Infinite concierge" },
      { en: "Travel insurance up to AED 2 million" },
      { en: "Hotel & dining discounts worldwide" },
    ],
    eligibilityCriteria: {
      minSalary: 30000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 6),
    category: "credit_card",
    nameEn: "Mashreq Cashback Card",
    nameAr: "بطاقة كاش باك من المشرق",
    descriptionEn: "Flat-rate cashback credit card from Mashreq with no annual fee for the first year.",
    provider: providers.mashreq,
    islamicCompliant: false,
    annualFee: "315",
    annualFeeWaiver: "Free first year",
    cashbackRate: "3",
    rewardType: "cashback",
    interestFreeGraceDays: 52,
    supplementaryCardFee: "0",
    minSalary: "8000",
    imageUrl: "/products/mashreq-cashback.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 315, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 200, type: "fixed" },
      { nameEn: "Cash Advance Fee", amount: 3, type: "percentage" },
    ],
    features: [
      { en: "Up to 3% cashback on dining" },
      { en: "1% cashback on all spends" },
      { en: "Free first year annual fee" },
      { en: "Free supplementary card" },
    ],
    eligibilityCriteria: {
      minSalary: 8000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 7),
    category: "credit_card",
    nameEn: "ADCB TouchPoints Infinite Card",
    nameAr: "بطاقة تاتش بوينتس انفينيت من أبوظبي التجاري",
    descriptionEn: "Earn TouchPoints on every purchase and redeem for flights, hotel stays, or shopping vouchers.",
    provider: providers.adcb,
    islamicCompliant: false,
    annualFee: "525",
    annualFeeWaiver: "Spend AED 150,000/year",
    rewardType: "points",
    rewardRate: "5",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "0",
    minSalary: "15000",
    imageUrl: "/products/adcb-touchpoints.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 525, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 2.75, type: "percentage" },
    ],
    features: [
      { en: "5x TouchPoints on dining & grocery" },
      { en: "2x TouchPoints on all other spends" },
      { en: "Airport lounge access (4 visits/year)" },
      { en: "Free supplementary card" },
      { en: "Redeem points for flights, stays, vouchers" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 8),
    category: "credit_card",
    nameEn: "ADCB Traveller Card",
    nameAr: "بطاقة ترافيلر من أبوظبي التجاري",
    descriptionEn: "Travel-focused credit card with no foreign exchange markup and free lounge access.",
    provider: providers.adcb,
    islamicCompliant: false,
    annualFee: "750",
    annualFeeWaiver: "Spend AED 200,000/year",
    rewardType: "miles",
    rewardRate: "2",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "250",
    minSalary: "20000",
    imageUrl: "/products/adcb-traveller.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 750, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 0, type: "percentage" },
    ],
    features: [
      { en: "0% foreign currency markup" },
      { en: "2x miles on all international spends" },
      { en: "Complimentary airport lounge access" },
      { en: "Travel insurance coverage included" },
      { en: "Free airport transfers (2/year)" },
    ],
    eligibilityCriteria: {
      minSalary: 20000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 9),
    category: "credit_card",
    nameEn: "RAKBANK World Mastercard",
    nameAr: "بطاقة وورلد ماستركارد من راك بنك",
    descriptionEn: "All-round credit card with cashback, lounge access, and low income requirement.",
    provider: providers.rakbank,
    islamicCompliant: false,
    annualFee: "500",
    annualFeeWaiver: "Spend AED 100,000/year",
    cashbackRate: "4",
    rewardType: "cashback",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "0",
    minSalary: "10000",
    imageUrl: "/products/rakbank-world.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 500, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 200, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 2.75, type: "percentage" },
    ],
    features: [
      { en: "Up to 4% cashback on dining" },
      { en: "1% cashback on everything else" },
      { en: "2 free airport lounge visits/year" },
      { en: "Free supplementary card" },
      { en: "Exclusive Mastercard World offers" },
    ],
    eligibilityCriteria: {
      minSalary: 10000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 10),
    category: "credit_card",
    nameEn: "DIB Prime Visa Infinite Card",
    nameAr: "بطاقة برايم فيزا انفينيت من بنك دبي الإسلامي",
    descriptionEn: "Premium Sharia-compliant credit card from DIB with luxury travel benefits and Visa Infinite perks.",
    provider: providers.dib,
    islamicCompliant: true,
    annualFee: "945",
    annualFeeWaiver: "Spend AED 200,000/year",
    rewardType: "points",
    rewardRate: "4",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "0",
    minSalary: "25000",
    imageUrl: "/products/dib-prime.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 945, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 250, type: "fixed" },
      { nameEn: "Cash Advance Fee", amount: 3, type: "percentage" },
    ],
    features: [
      { en: "Sharia-compliant — no interest charges" },
      { en: "4x reward points on travel & dining" },
      { en: "Unlimited airport lounge access" },
      { en: "Free supplementary card" },
      { en: "Visa Infinite luxury hotel collection" },
    ],
    eligibilityCriteria: {
      minSalary: 25000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 11),
    category: "credit_card",
    nameEn: "DIB Signature Card",
    nameAr: "بطاقة سيجنيتشر من بنك دبي الإسلامي",
    descriptionEn: "Sharia-compliant Visa Signature card with lifestyle benefits and competitive rewards.",
    provider: providers.dib,
    islamicCompliant: true,
    annualFee: "525",
    annualFeeWaiver: "Spend AED 120,000/year",
    rewardType: "points",
    rewardRate: "2",
    interestFreeGraceDays: 55,
    supplementaryCardFee: "0",
    minSalary: "12000",
    imageUrl: "/products/dib-signature.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 525, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 200, type: "fixed" },
    ],
    features: [
      { en: "Sharia-compliant" },
      { en: "2x reward points on all purchases" },
      { en: "Airport lounge access (4 visits/year)" },
      { en: "Free supplementary card" },
      { en: "Dining and lifestyle discounts" },
    ],
    eligibilityCriteria: {
      minSalary: 12000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("cc", 12),
    category: "credit_card",
    nameEn: "CBD World Mastercard",
    nameAr: "بطاقة وورلد ماستركارد من بنك دبي التجاري",
    descriptionEn: "CBD World Mastercard with generous rewards and low annual fee. Great for everyday spending.",
    provider: providers.cbd,
    islamicCompliant: false,
    annualFee: "420",
    annualFeeWaiver: "Spend AED 100,000/year",
    cashbackRate: "3",
    rewardType: "cashback",
    interestFreeGraceDays: 52,
    supplementaryCardFee: "0",
    minSalary: "10000",
    imageUrl: "/products/cbd-world.svg",
    fees: [
      { nameEn: "Annual Fee", amount: 420, type: "fixed" },
      { nameEn: "Late Payment Fee", amount: 225, type: "fixed" },
      { nameEn: "Foreign Currency Markup", amount: 2.75, type: "percentage" },
    ],
    features: [
      { en: "Up to 3% cashback on supermarkets & fuel" },
      { en: "1% cashback on all other spends" },
      { en: "Airport lounge access (2 visits/year)" },
      { en: "Free supplementary card" },
      { en: "Mastercard World privileges" },
    ],
    eligibilityCriteria: {
      minSalary: 10000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
];

/* ========================================================================== */
/*  MORTGAGES (8)                                                             */
/* ========================================================================== */

const mortgages: any[] = [
  {
    id: sid("mg", 1),
    category: "mortgage",
    nameEn: "Emirates NBD Home Loan",
    nameAr: "قرض السكن من بنك الإمارات دبي الوطني",
    descriptionEn: "Fixed-rate mortgage with low rates and flexible tenures up to 25 years for UAE residents and nationals.",
    provider: providers.enbd,
    islamicCompliant: false,
    rateType: "fixed" as const,
    rateValue: "3.990",
    minAmount: "200000",
    maxAmount: "15000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "15000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Property Valuation Fee", amount: 3000, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Fixed rate for up to 5 years" },
      { en: "Up to 80% LTV for UAE nationals" },
      { en: "Up to 75% LTV for expats" },
      { en: "Free property valuation" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("mg", 2),
    category: "mortgage",
    nameEn: "FAB Home Loan",
    nameAr: "قرض السكن من بنك أبوظبي الأول",
    descriptionEn: "First Abu Dhabi Bank mortgage with competitive rates starting from 3.49% and high loan amounts.",
    provider: providers.fab,
    islamicCompliant: false,
    rateType: "variable" as const,
    rateValue: "3.490",
    minAmount: "250000",
    maxAmount: "20000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "15000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Valuation Fee", amount: 2625, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Competitive variable rate from 3.49%" },
      { en: "Finance up to AED 20 million" },
      { en: "Up to 80% LTV for nationals" },
      { en: "Mortgage life insurance included" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("mg", 3),
    category: "mortgage",
    nameEn: "ADCB Home Loan",
    nameAr: "قرض السكن من بنك أبوظبي التجاري",
    descriptionEn: "ADCB mortgage with fixed-rate options, fast approval, and dedicated relationship managers.",
    provider: providers.adcb,
    islamicCompliant: false,
    rateType: "fixed" as const,
    rateValue: "3.990",
    minAmount: "200000",
    maxAmount: "15000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.05",
    earlySettlementFeePercent: "1.00",
    minSalary: "15000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.05, type: "percentage" },
      { nameEn: "Valuation Fee", amount: 3150, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Fixed rate for 1, 3, or 5 years" },
      { en: "Dedicated relationship manager" },
      { en: "Online mortgage calculator" },
      { en: "Pre-approval in 48 hours" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("mg", 4),
    category: "mortgage",
    nameEn: "Mashreq Home Loan",
    nameAr: "قرض السكن من بنك المشرق",
    descriptionEn: "Mashreq mortgage with flexible rate options and a streamlined digital application process.",
    provider: providers.mashreq,
    islamicCompliant: false,
    rateType: "variable" as const,
    rateValue: "4.250",
    minAmount: "200000",
    maxAmount: "10000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "15000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Valuation Fee", amount: 2625, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Digital mortgage application" },
      { en: "Flexible rate options" },
      { en: "Buyout existing mortgage at better rates" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("mg", 5),
    category: "mortgage",
    nameEn: "DIB Home Finance",
    nameAr: "تمويل السكن من بنك دبي الإسلامي",
    descriptionEn: "Sharia-compliant home finance from Dubai Islamic Bank based on Diminishing Musharaka structure.",
    provider: providers.dib,
    islamicCompliant: true,
    rateType: "reducing" as const,
    profitRate: "3.990",
    minAmount: "200000",
    maxAmount: "15000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "15000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Valuation Fee", amount: 2625, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Sharia-compliant Diminishing Musharaka" },
      { en: "Competitive profit rates" },
      { en: "Up to 80% finance for UAE nationals" },
      { en: "Free Takaful coverage" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("mg", 6),
    category: "mortgage",
    nameEn: "ADIB Home Finance",
    nameAr: "تمويل السكن من مصرف أبوظبي الإسلامي",
    descriptionEn: "ADIB Sharia-compliant home finance with fixed profit rates and tenure up to 25 years.",
    provider: providers.adib,
    islamicCompliant: true,
    rateType: "fixed" as const,
    profitRate: "4.250",
    minAmount: "200000",
    maxAmount: "10000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.05",
    earlySettlementFeePercent: "1.00",
    minSalary: "15000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.05, type: "percentage" },
      { nameEn: "Valuation Fee", amount: 3000, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Fixed profit rate for initial period" },
      { en: "Sharia-compliant Ijarah Muntahia Bittamleek" },
      { en: "Up to AED 10 million finance" },
      { en: "Free Takaful insurance" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("mg", 7),
    category: "mortgage",
    nameEn: "Emirates Islamic Home Finance",
    nameAr: "تمويل السكن من الإمارات الإسلامي",
    descriptionEn: "Emirates Islamic Sharia-compliant home finance with competitive profit rates and fast processing.",
    provider: providers.ei,
    islamicCompliant: true,
    rateType: "reducing" as const,
    profitRate: "3.750",
    minAmount: "200000",
    maxAmount: "12000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "15000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Valuation Fee", amount: 2625, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Competitive Islamic profit rates" },
      { en: "Part of Emirates NBD Group" },
      { en: "Quick pre-approval" },
      { en: "Suitable for ready and off-plan properties" },
    ],
    eligibilityCriteria: {
      minSalary: 15000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
  {
    id: sid("mg", 8),
    category: "mortgage",
    nameEn: "RAKBANK Home Loan",
    nameAr: "قرض السكن من راك بنك",
    descriptionEn: "RAKBANK mortgage with competitive rates and fast approvals for both UAE nationals and residents.",
    provider: providers.rakbank,
    islamicCompliant: false,
    rateType: "fixed" as const,
    rateValue: "4.490",
    minAmount: "150000",
    maxAmount: "10000000",
    minTenureMonths: 60,
    maxTenureMonths: 300,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "12000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Valuation Fee", amount: 2500, type: "fixed" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Fixed rate for initial period" },
      { en: "Lower minimum salary requirement" },
      { en: "Fast approval process" },
      { en: "Mortgage buyout option" },
    ],
    eligibilityCriteria: {
      minSalary: 12000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 12,
      minAge: 21,
    },
  },
];

/* ========================================================================== */
/*  AUTO LOANS (6)                                                            */
/* ========================================================================== */

const autoLoans: any[] = [
  {
    id: sid("al", 1),
    category: "auto_loan",
    nameEn: "Emirates NBD Auto Loan",
    nameAr: "قرض السيارات من بنك الإمارات دبي الوطني",
    descriptionEn: "Finance new and pre-owned vehicles with competitive rates and flexible repayment up to 60 months.",
    provider: providers.enbd,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "3.490",
    minAmount: "20000",
    maxAmount: "500000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Finance up to 80% of car value" },
      { en: "New and pre-owned vehicles" },
      { en: "Competitive reducing rate from 3.49%" },
      { en: "Quick approval process" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried", "Self-employed"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("al", 2),
    category: "auto_loan",
    nameEn: "FAB Auto Loan",
    nameAr: "قرض السيارات من بنك أبوظبي الأول",
    descriptionEn: "FAB auto loan with one of the lowest rates in the market and financing up to AED 500,000.",
    provider: providers.fab,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "2.990",
    minAmount: "20000",
    maxAmount: "500000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Lowest market rate from 2.99%" },
      { en: "Up to 80% finance for new cars" },
      { en: "Up to 60% for pre-owned cars" },
      { en: "Pre-approved offers for FAB customers" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("al", 3),
    category: "auto_loan",
    nameEn: "ADCB Auto Loan",
    nameAr: "قرض السيارات من بنك أبوظبي التجاري",
    descriptionEn: "ADCB auto finance with competitive rates, fast processing, and dealer partnerships across the UAE.",
    provider: providers.adcb,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "3.750",
    minAmount: "20000",
    maxAmount: "400000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Partnerships with major UAE dealers" },
      { en: "Free vehicle insurance for first year" },
      { en: "Quick disbursement" },
      { en: "Flexible tenure up to 60 months" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("al", 4),
    category: "auto_loan",
    nameEn: "Mashreq Auto Loan",
    nameAr: "قرض السيارات من بنك المشرق",
    descriptionEn: "Mashreq car loan with quick digital application and competitive rates for new vehicles.",
    provider: providers.mashreq,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "3.990",
    minAmount: "20000",
    maxAmount: "400000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.05",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.05, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Apply online or via Mashreq Neo app" },
      { en: "Finance up to 80% of vehicle value" },
      { en: "Approval within 30 minutes" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("al", 5),
    category: "auto_loan",
    nameEn: "DIB Auto Finance",
    nameAr: "تمويل السيارات من بنك دبي الإسلامي",
    descriptionEn: "Sharia-compliant vehicle finance from Dubai Islamic Bank with competitive profit rates.",
    provider: providers.dib,
    islamicCompliant: true,
    rateType: "reducing" as const,
    profitRate: "3.750",
    minAmount: "20000",
    maxAmount: "500000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "100% Sharia-compliant Murabaha" },
      { en: "Competitive profit rate" },
      { en: "New and pre-owned vehicles" },
      { en: "Free Takaful insurance" },
    ],
    eligibilityCriteria: {
      minSalary: 5000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
  {
    id: sid("al", 6),
    category: "auto_loan",
    nameEn: "RAKBANK Auto Loan",
    nameAr: "قرض السيارات من راك بنك",
    descriptionEn: "RAKBANK auto finance with low minimum salary requirement and quick digital application.",
    provider: providers.rakbank,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "4.250",
    minAmount: "15000",
    maxAmount: "350000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.00",
    earlySettlementFeePercent: "1.00",
    minSalary: "3000",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Low minimum salary — AED 3,000" },
      { en: "Apply online via RAKmobile" },
      { en: "Up to 80% finance" },
      { en: "Free registration and insurance coordination" },
    ],
    eligibilityCriteria: {
      minSalary: 3000,
      nationalities: ["All nationalities"],
      employmentTypes: ["Salaried"],
      minEmploymentMonths: 6,
      minAge: 21,
    },
  },
];

/* ========================================================================== */
/*  SAVINGS ACCOUNTS (6)                                                      */
/* ========================================================================== */

const savingsAccounts: any[] = [
  {
    id: sid("sa", 1),
    category: "savings_account",
    nameEn: "Emirates NBD Savings Account",
    nameAr: "حساب التوفير من بنك الإمارات دبي الوطني",
    descriptionEn: "Earn competitive interest on your savings with zero minimum balance and easy access to funds.",
    provider: providers.enbd,
    islamicCompliant: false,
    rateValue: "2.500",
    minAmount: "0",
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Up to 2.5% annual interest" },
      { en: "No minimum balance required" },
      { en: "Free online banking and mobile app" },
      { en: "Link to ENBD current account" },
    ],
    eligibilityCriteria: {
      minSalary: 0,
      nationalities: ["All nationalities"],
      minAge: 18,
    },
  },
  {
    id: sid("sa", 2),
    category: "savings_account",
    nameEn: "FAB Savings Account",
    nameAr: "حساب التوفير من بنك أبوظبي الأول",
    descriptionEn: "FAB savings account with tiered interest rates — earn more as your balance grows.",
    provider: providers.fab,
    islamicCompliant: false,
    rateValue: "3.000",
    minAmount: "3000",
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
      { nameEn: "Below Min Balance Fee", amount: 25, type: "fixed" },
    ],
    features: [
      { en: "Up to 3% annual interest on high balances" },
      { en: "Tiered interest structure" },
      { en: "Free debit card" },
      { en: "Manage via FAB Mobile" },
    ],
    eligibilityCriteria: {
      minSalary: 0,
      nationalities: ["All nationalities"],
      minAge: 18,
    },
  },
  {
    id: sid("sa", 3),
    category: "savings_account",
    nameEn: "ADCB Savings Account",
    nameAr: "حساب التوفير من بنك أبوظبي التجاري",
    descriptionEn: "ADCB savings account with competitive rates and integrated TouchPoints rewards.",
    provider: providers.adcb,
    islamicCompliant: false,
    rateValue: "2.000",
    minAmount: "3000",
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Up to 2% annual interest" },
      { en: "Earn ADCB TouchPoints" },
      { en: "Free transfers between ADCB accounts" },
      { en: "Online goal-based savings" },
    ],
    eligibilityCriteria: {
      minSalary: 0,
      nationalities: ["All nationalities"],
      minAge: 18,
    },
  },
  {
    id: sid("sa", 4),
    category: "savings_account",
    nameEn: "Mashreq Neo Savings",
    nameAr: "حساب توفير مشرق نيو",
    descriptionEn: "Digital-first savings account from Mashreq with attractive rates and zero paperwork.",
    provider: providers.mashreq,
    islamicCompliant: false,
    rateValue: "3.500",
    minAmount: "0",
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Up to 3.5% annual interest" },
      { en: "Open account in minutes via app" },
      { en: "Zero minimum balance" },
      { en: "Instant fund transfers" },
    ],
    eligibilityCriteria: {
      minSalary: 0,
      nationalities: ["All nationalities"],
      minAge: 18,
    },
  },
  {
    id: sid("sa", 5),
    category: "savings_account",
    nameEn: "Wio Save",
    nameAr: "حساب التوفير من ويو",
    descriptionEn: "Digital bank savings account from Wio with one of the highest interest rates in the UAE.",
    provider: providers.wio,
    islamicCompliant: false,
    rateValue: "4.500",
    minAmount: "0",
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "4.5% annual interest — highest in UAE" },
      { en: "No minimum balance" },
      { en: "100% digital — open in 5 minutes" },
      { en: "CBUAE regulated" },
      { en: "Instant withdrawals to Wio current account" },
    ],
    eligibilityCriteria: {
      minSalary: 0,
      nationalities: ["UAE nationals", "UAE residents"],
      minAge: 18,
    },
  },
  {
    id: sid("sa", 6),
    category: "savings_account",
    nameEn: "Liv. Savings Account",
    nameAr: "حساب التوفير من ليف",
    descriptionEn: "Liv. digital savings account by Emirates NBD with competitive rates and a fully digital experience.",
    provider: providers.liv,
    islamicCompliant: false,
    rateValue: "3.000",
    minAmount: "0",
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Up to 3% annual interest" },
      { en: "Goal-based savings pots" },
      { en: "Zero fees on everything" },
      { en: "Social banking features" },
    ],
    eligibilityCriteria: {
      minSalary: 0,
      nationalities: ["All nationalities"],
      minAge: 18,
    },
  },
];

/* ========================================================================== */
/*  CAR INSURANCE (4)                                                         */
/* ========================================================================== */

const carInsurance: any[] = [
  {
    id: sid("ci", 1),
    category: "car_insurance",
    nameEn: "Sukoon Comprehensive Motor Insurance",
    nameAr: "تأمين سيارات شامل من سكون",
    descriptionEn: "Comprehensive car insurance covering own damage, third-party liability, and personal accident.",
    provider: providers.sukoon,
    islamicCompliant: false,
    premiumMin: "1200",
    coverageAmount: "500000",
    imageUrl: null,
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 30, type: "fixed" },
    ],
    features: [
      { en: "Comprehensive own damage cover" },
      { en: "Third-party liability up to AED 500,000" },
      { en: "Personal accident cover for driver and passengers" },
      { en: "24/7 roadside assistance" },
      { en: "Agency and non-agency repair options" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("ci", 2),
    category: "car_insurance",
    nameEn: "Orient Comprehensive Motor Insurance",
    nameAr: "تأمين سيارات شامل من أورينت",
    descriptionEn: "Orient Insurance comprehensive motor cover with competitive premiums and fast claims settlement.",
    provider: providers.orient,
    islamicCompliant: false,
    premiumMin: "1000",
    coverageAmount: "500000",
    imageUrl: null,
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 35, type: "fixed" },
    ],
    features: [
      { en: "Comprehensive and third-party options" },
      { en: "Fast claims processing" },
      { en: "Windshield cover included" },
      { en: "Oman extension available" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("ci", 3),
    category: "car_insurance",
    nameEn: "AXA SmartDrive Motor Insurance",
    nameAr: "تأمين سيارات سمارت درايف من أكسا",
    descriptionEn: "AXA SmartDrive comprehensive motor insurance with flexible add-ons and dedicated claims support.",
    provider: providers.axa,
    islamicCompliant: false,
    premiumMin: "1100",
    coverageAmount: "500000",
    imageUrl: null,
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 30, type: "fixed" },
    ],
    features: [
      { en: "Flexible add-on covers" },
      { en: "Dedicated claims manager" },
      { en: "Replacement car during repairs" },
      { en: "Personal belongings cover" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("ci", 4),
    category: "car_insurance",
    nameEn: "ADNIC Comprehensive Motor Insurance",
    nameAr: "تأمين سيارات شامل من أدنيك",
    descriptionEn: "Abu Dhabi National Insurance Company comprehensive auto cover with wide garage network.",
    provider: providers.adnic,
    islamicCompliant: false,
    premiumMin: "1050",
    coverageAmount: "500000",
    imageUrl: null,
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 25, type: "fixed" },
    ],
    features: [
      { en: "Wide network of approved garages" },
      { en: "Natural calamity coverage" },
      { en: "Off-road coverage optional add-on" },
      { en: "Quick online quotation" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
];

/* ========================================================================== */
/*  HEALTH INSURANCE (4)                                                      */
/* ========================================================================== */

const healthInsurance: any[] = [
  {
    id: sid("hi", 1),
    category: "health_insurance",
    nameEn: "Daman Enhanced Health Insurance",
    nameAr: "تأمين صحي محسّن من ضمان",
    descriptionEn: "Enhanced health insurance plan by Daman with extensive hospital network and comprehensive outpatient coverage.",
    provider: providers.daman,
    islamicCompliant: false,
    premiumMin: "3500",
    coverageAmount: "1000000",
    imageUrl: null,
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Inpatient and outpatient coverage" },
      { en: "Dental and optical included" },
      { en: "Maternity coverage available" },
      { en: "Largest hospital network in UAE" },
      { en: "DHA and HAAD compliant" },
    ],
    eligibilityCriteria: {
      minAge: 0,
    },
  },
  {
    id: sid("hi", 2),
    category: "health_insurance",
    nameEn: "AXA Gold Health Insurance",
    nameAr: "تأمين صحي ذهبي من أكسا",
    descriptionEn: "AXA Gold health plan with worldwide coverage, direct billing, and wellness benefits.",
    provider: providers.axa,
    islamicCompliant: false,
    premiumMin: "4500",
    coverageAmount: "2000000",
    imageUrl: null,
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Worldwide emergency coverage" },
      { en: "Direct billing at 1000+ facilities" },
      { en: "Annual health check-up included" },
      { en: "Mental health coverage" },
      { en: "Wellness and preventive care" },
    ],
    eligibilityCriteria: {
      minAge: 0,
    },
  },
  {
    id: sid("hi", 3),
    category: "health_insurance",
    nameEn: "Sukoon Family Health Insurance",
    nameAr: "تأمين صحي عائلي من سكون",
    descriptionEn: "Sukoon family health insurance with competitive premiums and comprehensive family coverage.",
    provider: providers.sukoon,
    islamicCompliant: false,
    premiumMin: "3000",
    coverageAmount: "1000000",
    imageUrl: null,
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Family coverage — spouse and children" },
      { en: "Outpatient and inpatient care" },
      { en: "Dental and optical coverage" },
      { en: "Maternity benefits included" },
    ],
    eligibilityCriteria: {
      minAge: 0,
    },
  },
  {
    id: sid("hi", 4),
    category: "health_insurance",
    nameEn: "Orient Comprehensive Health Insurance",
    nameAr: "تأمين صحي شامل من أورينت",
    descriptionEn: "Orient Insurance comprehensive health plan with affordable premiums and wide provider network.",
    provider: providers.orient,
    islamicCompliant: false,
    premiumMin: "2500",
    coverageAmount: "500000",
    imageUrl: null,
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Affordable premium options" },
      { en: "Wide network of hospitals and clinics" },
      { en: "Prescription medication coverage" },
      { en: "Emergency ambulance service" },
    ],
    eligibilityCriteria: {
      minAge: 0,
    },
  },
];

/* ========================================================================== */
/*  MOBILE PLANS (6)                                                          */
/* ========================================================================== */

const mobilePlans: any[] = [
  {
    id: sid("mp", 1),
    category: "mobile_plan",
    nameEn: "du Power Plan 200",
    nameAr: "خطة باور 200 من دو",
    descriptionEn: "du postpaid plan with generous data allowance, unlimited local calls, and entertainment perks.",
    provider: providers.du,
    islamicCompliant: false,
    priceMonthly: "200",
    dataGb: "40",
    minutes: "unlimited",
    contractMonths: 12,
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Subscription", amount: 200, type: "fixed" },
      { nameEn: "SIM Card Fee", amount: 55, type: "fixed" },
    ],
    features: [
      { en: "40 GB monthly data" },
      { en: "Unlimited local calls" },
      { en: "Free OSN streaming" },
      { en: "Data rollover to next month" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("mp", 2),
    category: "mobile_plan",
    nameEn: "du Flex Plan 100",
    nameAr: "خطة فلكس 100 من دو",
    descriptionEn: "Budget-friendly du postpaid plan with 10 GB data and flexible national minutes.",
    provider: providers.du,
    islamicCompliant: false,
    priceMonthly: "100",
    dataGb: "10",
    minutes: "250",
    contractMonths: 12,
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Subscription", amount: 100, type: "fixed" },
      { nameEn: "SIM Card Fee", amount: 55, type: "fixed" },
    ],
    features: [
      { en: "10 GB monthly data" },
      { en: "250 national minutes" },
      { en: "Unlimited du-to-du calls" },
      { en: "No commitment plans available" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("mp", 3),
    category: "mobile_plan",
    nameEn: "e& Unlimited Plan 300",
    nameAr: "خطة أنليمتد 300 من اتصالات",
    descriptionEn: "Premium e& (Etisalat) postpaid plan with unlimited data, calls, and exclusive perks.",
    provider: providers.etisalat,
    islamicCompliant: false,
    priceMonthly: "300",
    dataGb: "unlimited",
    minutes: "unlimited",
    contractMonths: 12,
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Subscription", amount: 300, type: "fixed" },
      { nameEn: "SIM Card Fee", amount: 55, type: "fixed" },
    ],
    features: [
      { en: "Unlimited data" },
      { en: "Unlimited local and national calls" },
      { en: "Free roaming in select countries" },
      { en: "Starzplay and other OTT subscriptions included" },
      { en: "Premium customer service" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("mp", 4),
    category: "mobile_plan",
    nameEn: "e& Go Plan 150",
    nameAr: "خطة جو 150 من اتصالات",
    descriptionEn: "Mid-tier e& (Etisalat) postpaid plan with balanced data, calls, and entertainment bundles.",
    provider: providers.etisalat,
    islamicCompliant: false,
    priceMonthly: "150",
    dataGb: "20",
    minutes: "unlimited",
    contractMonths: 12,
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Subscription", amount: 150, type: "fixed" },
      { nameEn: "SIM Card Fee", amount: 55, type: "fixed" },
    ],
    features: [
      { en: "20 GB monthly data" },
      { en: "Unlimited local calls" },
      { en: "Free Anghami Plus subscription" },
      { en: "Data rollover available" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("mp", 5),
    category: "mobile_plan",
    nameEn: "Virgin Mobile Go Big 199",
    nameAr: "خطة جو بيج 199 من فيرجن موبايل",
    descriptionEn: "Flexible SIM-only plan from Virgin Mobile UAE with generous data and zero commitment.",
    provider: providers.virgin,
    islamicCompliant: false,
    priceMonthly: "199",
    dataGb: "50",
    minutes: "unlimited",
    contractMonths: 0,
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Subscription", amount: 199, type: "fixed" },
    ],
    features: [
      { en: "50 GB monthly data" },
      { en: "Unlimited local calls & SMS" },
      { en: "No contract — cancel anytime" },
      { en: "Manage everything via app" },
      { en: "Free eSIM activation" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("mp", 6),
    category: "mobile_plan",
    nameEn: "Virgin Mobile Start 59",
    nameAr: "خطة ستارت 59 من فيرجن موبايل",
    descriptionEn: "Affordable SIM-only plan from Virgin Mobile for light users. No contract needed.",
    provider: providers.virgin,
    islamicCompliant: false,
    priceMonthly: "59",
    dataGb: "3",
    minutes: "60",
    contractMonths: 0,
    imageUrl: null,
    fees: [
      { nameEn: "Monthly Subscription", amount: 59, type: "fixed" },
    ],
    features: [
      { en: "3 GB monthly data" },
      { en: "60 national minutes" },
      { en: "No contract — cancel anytime" },
      { en: "Manage everything via app" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
];

/* ========================================================================== */
/*  FIXED DEPOSITS (3)                                                        */
/* ========================================================================== */

const fixedDeposits: any[] = [
  {
    id: sid("fd", 1),
    category: "fixed_deposit",
    nameEn: "Emirates NBD Fixed Deposit",
    nameAr: "وديعة ثابتة من بنك الإمارات دبي الوطني",
    descriptionEn: "Secure your savings with Emirates NBD fixed deposit offering guaranteed returns and flexible tenures.",
    provider: providers.enbd,
    islamicCompliant: false,
    rateValue: "4.250",
    minAmount: "10000",
    minTenureMonths: 1,
    maxTenureMonths: 60,
    imageUrl: null,
    fees: [],
    features: [
      { en: "Guaranteed returns up to 4.25% p.a." },
      { en: "Tenures from 1 month to 5 years" },
      { en: "Auto-renewal option" },
      { en: "Capital protection — zero risk" },
    ],
    eligibilityCriteria: {
      minAge: 18,
      nationalities: ["All nationalities"],
    },
  },
  {
    id: sid("fd", 2),
    category: "fixed_deposit",
    nameEn: "FAB Term Deposit",
    nameAr: "وديعة لأجل من بنك أبوظبي الأول",
    descriptionEn: "FAB term deposit with attractive interest rates and the safety of the largest UAE bank.",
    provider: providers.fab,
    islamicCompliant: false,
    rateValue: "4.500",
    minAmount: "10000",
    minTenureMonths: 1,
    maxTenureMonths: 60,
    imageUrl: null,
    fees: [],
    features: [
      { en: "Up to 4.5% annual interest" },
      { en: "Backed by the UAE's largest bank" },
      { en: "Flexible tenure options" },
      { en: "Loan against deposit available" },
    ],
    eligibilityCriteria: {
      minAge: 18,
      nationalities: ["All nationalities"],
    },
  },
  {
    id: sid("fd", 3),
    category: "fixed_deposit",
    nameEn: "Mashreq Fixed Deposit",
    nameAr: "وديعة ثابتة من بنك المشرق",
    descriptionEn: "Mashreq bank fixed deposit with competitive rates and convenient online management.",
    provider: providers.mashreq,
    islamicCompliant: false,
    rateValue: "4.000",
    minAmount: "5000",
    minTenureMonths: 1,
    maxTenureMonths: 36,
    imageUrl: null,
    fees: [],
    features: [
      { en: "Up to 4% annual interest" },
      { en: "Lower minimum deposit at AED 5,000" },
      { en: "Manage via Mashreq Neo app" },
      { en: "Auto-renewal with updated rates" },
    ],
    eligibilityCriteria: {
      minAge: 18,
      nationalities: ["All nationalities"],
    },
  },
];

/* ========================================================================== */
/*  LIFE INSURANCE (3)                                                        */
/* ========================================================================== */

const lifeInsurance: any[] = [
  {
    id: sid("li", 1),
    category: "life_insurance",
    nameEn: "AXA Term Life Insurance",
    nameAr: "تأمين على الحياة لأجل من أكسا",
    descriptionEn: "AXA term life insurance providing financial protection for your family with affordable premiums.",
    provider: providers.axa,
    islamicCompliant: false,
    premiumMin: "1500",
    coverageAmount: "1000000",
    imageUrl: null,
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Coverage up to AED 1 million" },
      { en: "Affordable premiums from AED 1,500/year" },
      { en: "Critical illness add-on available" },
      { en: "Worldwide coverage" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("li", 2),
    category: "life_insurance",
    nameEn: "Sukoon Whole Life Takaful",
    nameAr: "تكافل حياة كاملة من سكون",
    descriptionEn: "Sharia-compliant whole life Takaful plan providing lifelong coverage and savings.",
    provider: providers.sukoon,
    islamicCompliant: true,
    premiumMin: "3000",
    coverageAmount: "2000000",
    imageUrl: null,
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Sharia-compliant Takaful structure" },
      { en: "Lifelong coverage" },
      { en: "Savings component with profit sharing" },
      { en: "Coverage up to AED 2 million" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("li", 3),
    category: "life_insurance",
    nameEn: "Orient Term Life Plan",
    nameAr: "خطة تأمين على الحياة لأجل من أورينت",
    descriptionEn: "Orient term life insurance with competitive premiums and optional riders for critical illness.",
    provider: providers.orient,
    islamicCompliant: false,
    premiumMin: "1200",
    coverageAmount: "750000",
    imageUrl: null,
    fees: [
      { nameEn: "Policy Issuance Fee", amount: 0, type: "fixed" },
    ],
    features: [
      { en: "Term coverage up to 30 years" },
      { en: "Affordable premiums" },
      { en: "Critical illness rider available" },
      { en: "Disability benefit option" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
];

/* ========================================================================== */
/*  TRAVEL INSURANCE (3)                                                      */
/* ========================================================================== */

const travelInsurance: any[] = [
  {
    id: sid("ti", 1),
    category: "travel_insurance",
    nameEn: "AXA SmartTraveller Insurance",
    nameAr: "تأمين السفر سمارت ترافيلر من أكسا",
    descriptionEn: "Comprehensive travel insurance covering medical emergencies, trip cancellation, and lost luggage.",
    provider: providers.axa,
    islamicCompliant: false,
    premiumMin: "500",
    coverageAmount: "500000",
    imageUrl: null,
    fees: [],
    features: [
      { en: "Medical emergency cover up to AED 500,000" },
      { en: "Trip cancellation and delay cover" },
      { en: "Lost and delayed luggage cover" },
      { en: "24/7 worldwide assistance" },
    ],
    eligibilityCriteria: {
      minAge: 0,
    },
  },
  {
    id: sid("ti", 2),
    category: "travel_insurance",
    nameEn: "Sukoon Travel Insurance",
    nameAr: "تأمين السفر من سكون",
    descriptionEn: "Sukoon travel insurance for individuals and families with single trip and annual multi-trip options.",
    provider: providers.sukoon,
    islamicCompliant: false,
    premiumMin: "400",
    coverageAmount: "250000",
    imageUrl: null,
    fees: [],
    features: [
      { en: "Single trip and annual multi-trip plans" },
      { en: "Medical evacuation coverage" },
      { en: "Personal liability cover" },
      { en: "Family plan discounts" },
    ],
    eligibilityCriteria: {
      minAge: 0,
    },
  },
  {
    id: sid("ti", 3),
    category: "travel_insurance",
    nameEn: "Orient Travel Insurance",
    nameAr: "تأمين السفر من أورينت",
    descriptionEn: "Orient Insurance travel plan with affordable premiums and worldwide coverage.",
    provider: providers.orient,
    islamicCompliant: false,
    premiumMin: "350",
    coverageAmount: "200000",
    imageUrl: null,
    fees: [],
    features: [
      { en: "Worldwide medical emergency cover" },
      { en: "Affordable premiums from AED 350" },
      { en: "Schengen visa compliant" },
      { en: "Online purchase and instant policy" },
    ],
    eligibilityCriteria: {
      minAge: 0,
    },
  },
];

/* ========================================================================== */
/*  HOME INSURANCE (3)                                                        */
/* ========================================================================== */

const homeInsurance: any[] = [
  {
    id: sid("ho", 1),
    category: "home_insurance",
    nameEn: "AXA Smart Home Insurance",
    nameAr: "تأمين المنزل الذكي من أكسا",
    descriptionEn: "Comprehensive home insurance from AXA covering building, contents, and personal liability.",
    provider: providers.axa,
    islamicCompliant: false,
    premiumMin: "800",
    coverageAmount: "1000000",
    imageUrl: null,
    fees: [],
    features: [
      { en: "Building and contents coverage" },
      { en: "Personal liability protection" },
      { en: "Domestic worker cover" },
      { en: "Alternative accommodation if home is uninhabitable" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("ho", 2),
    category: "home_insurance",
    nameEn: "ADNIC Home Insurance",
    nameAr: "تأمين المنزل من أدنيك",
    descriptionEn: "ADNIC home insurance protecting your property and belongings against fire, theft, and natural disasters.",
    provider: providers.adnic,
    islamicCompliant: false,
    premiumMin: "600",
    coverageAmount: "750000",
    imageUrl: null,
    fees: [],
    features: [
      { en: "Fire, theft, and natural disaster coverage" },
      { en: "Tenant and landlord options" },
      { en: "Jewellery and valuables rider" },
      { en: "Affordable premiums" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("ho", 3),
    category: "home_insurance",
    nameEn: "Sukoon Home Insurance",
    nameAr: "تأمين المنزل من سكون",
    descriptionEn: "Sukoon home insurance with flexible plans for owners and tenants in the UAE.",
    provider: providers.sukoon,
    islamicCompliant: false,
    premiumMin: "700",
    coverageAmount: "500000",
    imageUrl: null,
    fees: [],
    features: [
      { en: "Owner and tenant plans" },
      { en: "Contents and building coverage" },
      { en: "Water damage protection" },
      { en: "Third-party liability" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
];

/* ========================================================================== */
/*  BNPL — BUY NOW PAY LATER (3)                                              */
/* ========================================================================== */

const bnpl: any[] = [
  {
    id: sid("bn", 1),
    category: "bnpl",
    nameEn: "Tabby — Pay in 4",
    descriptionEn: "Split any purchase into 4 interest-free payments with Tabby. No hidden fees.",
    provider: { nameEn: "Tabby", logoUrl: "/logos/tabby.svg", website: "https://tabby.ai" },
    islamicCompliant: true,
    minAmount: "1",
    maxAmount: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Late Fee", amount: 25, type: "fixed" },
    ],
    features: [
      { en: "Split into 4 interest-free payments" },
      { en: "No hidden fees if you pay on time" },
      { en: "Works at 10,000+ UAE stores" },
      { en: "Sharia-compliant — certified by scholars" },
      { en: "Instant approval" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("bn", 2),
    category: "bnpl",
    nameEn: "Tamara — Pay Later",
    descriptionEn: "Shop now and pay later in 3 installments with zero interest using Tamara.",
    provider: { nameEn: "Tamara", logoUrl: "/logos/tamara.svg", website: "https://tamara.co" },
    islamicCompliant: true,
    minAmount: "1",
    maxAmount: "4000",
    imageUrl: null,
    fees: [
      { nameEn: "Late Fee", amount: 25, type: "fixed" },
    ],
    features: [
      { en: "Pay in 3 installments — 0% interest" },
      { en: "Sharia-compliant" },
      { en: "Available at major UAE retailers" },
      { en: "Quick sign-up via app" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
  {
    id: sid("bn", 3),
    category: "bnpl",
    nameEn: "Postpay — Buy Now, Pay Later",
    descriptionEn: "Postpay lets you split your purchase into 3 interest-free payments at checkout.",
    provider: { nameEn: "Postpay", logoUrl: "/logos/postpay.svg", website: "https://postpay.io" },
    islamicCompliant: false,
    minAmount: "1",
    maxAmount: "3000",
    imageUrl: null,
    fees: [
      { nameEn: "Late Fee", amount: 20, type: "fixed" },
    ],
    features: [
      { en: "3 interest-free installments" },
      { en: "Available at 1,000+ stores in UAE" },
      { en: "Seamless online checkout integration" },
      { en: "Instant credit decision" },
    ],
    eligibilityCriteria: {
      minAge: 18,
    },
  },
];

/* ========================================================================== */
/*  INVESTMENT ACCOUNTS (3)                                                   */
/* ========================================================================== */

const investmentAccounts: any[] = [
  {
    id: sid("ia", 1),
    category: "investment_account",
    nameEn: "ENBD Securities Trading Account",
    nameAr: "حساب تداول الأوراق المالية من بنك الإمارات دبي الوطني",
    descriptionEn: "Trade UAE, GCC, and international equities with Emirates NBD Securities brokerage account.",
    provider: providers.enbd,
    islamicCompliant: false,
    minAmount: "5000",
    imageUrl: null,
    fees: [
      { nameEn: "Account Opening Fee", amount: 0, type: "fixed" },
      { nameEn: "Brokerage Fee (UAE)", amount: 0.15, type: "percentage" },
      { nameEn: "Brokerage Fee (International)", amount: 0.25, type: "percentage" },
    ],
    features: [
      { en: "Trade on DFM, ADX, and Nasdaq Dubai" },
      { en: "Access to international markets" },
      { en: "Research reports and market insights" },
      { en: "Mobile trading app" },
    ],
    eligibilityCriteria: {
      minAge: 21,
      nationalities: ["All nationalities"],
    },
  },
  {
    id: sid("ia", 2),
    category: "investment_account",
    nameEn: "FAB Invest Account",
    nameAr: "حساب الاستثمار من بنك أبوظبي الأول",
    descriptionEn: "FAB investment account offering mutual funds, bonds, and structured products managed by wealth experts.",
    provider: providers.fab,
    islamicCompliant: false,
    minAmount: "10000",
    imageUrl: null,
    fees: [
      { nameEn: "Account Maintenance Fee", amount: 0, type: "fixed" },
      { nameEn: "Fund Management Fee", amount: 1.5, type: "percentage" },
    ],
    features: [
      { en: "Wide range of mutual funds and ETFs" },
      { en: "Bonds and fixed-income products" },
      { en: "Dedicated wealth advisor" },
      { en: "Online portfolio tracking" },
    ],
    eligibilityCriteria: {
      minAge: 21,
      nationalities: ["All nationalities"],
    },
  },
  {
    id: sid("ia", 3),
    category: "investment_account",
    nameEn: "ADCB Invest Account",
    nameAr: "حساب الاستثمار من بنك أبوظبي التجاري",
    descriptionEn: "ADCB investment account with access to mutual funds, equities, and structured deposits.",
    provider: providers.adcb,
    islamicCompliant: false,
    minAmount: "10000",
    imageUrl: null,
    fees: [
      { nameEn: "Account Fee", amount: 0, type: "fixed" },
      { nameEn: "Advisory Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Diverse asset class exposure" },
      { en: "Robo-advisory option available" },
      { en: "Structured deposits with capital protection" },
      { en: "Regular investment plans" },
    ],
    eligibilityCriteria: {
      minAge: 21,
      nationalities: ["All nationalities"],
    },
  },
];

/* ========================================================================== */
/*  BUSINESS LOANS (3)                                                        */
/* ========================================================================== */

const businessLoans: any[] = [
  {
    id: sid("bl", 1),
    category: "business_loan",
    nameEn: "Emirates NBD Business Loan",
    nameAr: "قرض الأعمال من بنك الإمارات دبي الوطني",
    descriptionEn: "Working capital and expansion financing for SMEs with competitive rates and minimal documentation.",
    provider: providers.enbd,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "5.490",
    minAmount: "100000",
    maxAmount: "5000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.50",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.5, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Financing from AED 100K to AED 5M" },
      { en: "Minimal documentation required" },
      { en: "Flexible repayment terms" },
      { en: "Dedicated SME relationship manager" },
    ],
    eligibilityCriteria: {
      minAge: 21,
      employmentTypes: ["Business owner"],
      minEmploymentMonths: 24,
    },
  },
  {
    id: sid("bl", 2),
    category: "business_loan",
    nameEn: "FAB SME Business Finance",
    nameAr: "تمويل الأعمال الصغيرة من بنك أبوظبي الأول",
    descriptionEn: "FAB business loan for small and medium enterprises with quick processing and collateral-free options.",
    provider: providers.fab,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "4.990",
    minAmount: "100000",
    maxAmount: "10000000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    processingFeePercent: "1.25",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.25, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1, type: "percentage" },
    ],
    features: [
      { en: "Finance up to AED 10 million" },
      { en: "Collateral-free options for eligible SMEs" },
      { en: "Quick disbursement" },
      { en: "Trade finance and overdraft facilities" },
    ],
    eligibilityCriteria: {
      minAge: 21,
      employmentTypes: ["Business owner"],
      minEmploymentMonths: 12,
    },
  },
  {
    id: sid("bl", 3),
    category: "business_loan",
    nameEn: "Mashreq Business Banking Loan",
    nameAr: "قرض الأعمال المصرفية من المشرق",
    descriptionEn: "Mashreq business loan offering working capital and asset finance for growing businesses.",
    provider: providers.mashreq,
    islamicCompliant: false,
    rateType: "reducing" as const,
    rateValue: "5.250",
    minAmount: "50000",
    maxAmount: "3000000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    processingFeePercent: "1.50",
    imageUrl: null,
    fees: [
      { nameEn: "Processing Fee", amount: 1.5, type: "percentage" },
      { nameEn: "Early Settlement Fee", amount: 1.5, type: "percentage" },
    ],
    features: [
      { en: "Working capital and asset finance" },
      { en: "Digital application via Mashreq Business Banking" },
      { en: "Quick turnaround time" },
      { en: "Available to free zone companies" },
    ],
    eligibilityCriteria: {
      minAge: 21,
      employmentTypes: ["Business owner"],
      minEmploymentMonths: 12,
    },
  },
];

/* ========================================================================== */
/*  CATEGORY MAP                                                              */
/* ========================================================================== */

const categoryMap: Record<string, any[]> = {
  personal_loan: personalLoans,
  credit_card: creditCards,
  mortgage: mortgages,
  auto_loan: autoLoans,
  savings_account: savingsAccounts,
  car_insurance: carInsurance,
  health_insurance: healthInsurance,
  mobile_plan: mobilePlans,
  fixed_deposit: fixedDeposits,
  life_insurance: lifeInsurance,
  travel_insurance: travelInsurance,
  home_insurance: homeInsurance,
  bnpl: bnpl,
  investment_account: investmentAccounts,
  business_loan: businessLoans,
};

/* ========================================================================== */
/*  PUBLIC API                                                                */
/* ========================================================================== */

/**
 * Returns an array of product objects for the given category.
 * Falls back to an empty array for unknown / empty categories.
 */
export function getStaticProducts(category: string): any[] {
  return categoryMap[category] ?? [];
}
